### ISSUE TITLE
Avoid changing buffer on error

### ISSUE THREAD

**Issue by tmatth** [Chiel92/vim-autoformat#10]
Great plugin, super useful.

One issue I had is that if for some reason astyle errors out, it will replace my buffer with whatever error message it produced. To reproduce, if you add --foobar or some other bad option to format args, the buffer will be replaced by:

> Invalid command line options:
> foobar
>
> For help on options type 'astyle -h'
>
> Artistic Style has terminated

Would it be possible to restore the original buffer if the formatter returned 1?

**Comment by Chiel92** [comment]
This should be fixed in the new update.
