### ISSUE TITLE
:Autoformat results do not match clang-format output

### ISSUE THREAD

**Issue by lawshoe** [Chiel92/vim-autoformat#100]
Great Plugin.  Echoing g:formatdef_clangformat indicates that the style is based on webkit even though the .clang-format file is for google or llvm.  I do have the "let g:formatdef_clangformat_objc = '"clang-format -style=file"' line in my .vimrc.  I have verified clang-format from the command line and it works fine.   What have I done wrong?

**Comment by Chiel92** [comment]
If you set the verbose flag (`:set verbose=1`) before running the formatter, do you get additional output?
Related: https://github.com/Chiel92/vim-autoformat/issues/95

**Comment by lawshoe** [comment]
Nope

**Comment by Chiel92** [comment]
Only now I see that you did not get the right variable name.
If you want to override the clangformat definition, you have to set `let g:formatdef_clangformat =  '"clang-format -style=file"'`.
Alternatively you can define you own, e.g. `g:formatdef_myclang`, and add it to the objective c formatter list, like `let g:formatters_objc = ['myclang']`.

**Comment by lawshoe** [comment]
I found some odd behavior.  In order to check that things are working I am switching between the llvm style (pointer is on the right) and the google style (pointer is on the left).  I write out a .clang-format file, open an empty main.cpp file, call :Autoformat and watch the pointer in the char * argv[] argument of main.  

In my .vimrc if I have g:formatdef_clangformat = '"clang-format -style=file"' the google style works.  If I comment out that and let g:formatdef_clangformat_cpp = '"clang-format -style=file"' then the llvm style works.

I also had to add 'clangformat' to my formatterpath instead of 'clang-format'.

Is there any way to verify which formatter is actually being used?

**Comment by Chiel92** [comment]
After you ran the formatter you can see which definition was use by running `:echo &formatprg`.

**Comment by dragonxlwang** [comment]
it seems the only way to change format style for clange is by @lawshoe 
```
let g:formatdef_clangformat_cpp = '"clang-format -style=google"' 
```
The one noted in the markdown doesn't work somehow...

**Comment by Chiel92** [comment]
What's with the `let g:formatdef_clangformat_cpp` all the time :D.

The right way to do it is 

```
let g:formatdef_my_custom_clang = '"clang-format -style=google"' 
let g:formatters_cpp = ['my_custom_clang']
```

**Comment by dragonxlwang** [comment]
@Chiel92 , that works! Thanks!
