### ISSUE TITLE
Thoughts on Replacing Default Ruby Formatter

### ISSUE THREAD

**Issue by sbdchd** [Chiel92/vim-autoformat#103]
I was wondering what your thoughts would be on replacing [ruby-beautify](https://github.com/erniebrodeur/ruby-beautify) with [rubocop](https://github.com/bbatsov/rubocop).

They both get the job done, but rubocop seems more active.

**Comment by Chiel92** [comment]
Vim-autoformat allows to have multiple formatter defaults per filetype. For instance, have a look in `defauls.vim` in de section where the `C` formatters are defined.

```vim
if !exists('g:formatters_c')
    let g:formatters_c = ['clangformat', 'astyle_c']
endif
```

So in a pull request you can just provide a default definition in `g:formatdef_rubocop` and a add it to the list of ruby formatters `g:formatters_ruby`
