### ISSUE TITLE
Allow specifying extra options on top of the defaults for some formatters

### ISSUE THREAD

**Issue by svenstaro** [Chiel92/vim-autoformat#104]
So I think it would make sense if one didn't have to overwrite all of a formatter's options in order to customize it. I think, for instance in the case of clangformat, it would make much more sense to allow for defining something like `extraoptions` that would be appended after the defaults. For instance, this is like vim-clang-format does it [0] and I think it makes quite a bit of sense. It would also allow for a better format when specifying options. As it stands, the line might get quite absurd.

[0] https://github.com/rhysd/vim-clang-format/blob/master/autoload/clang_format.vim#L53

**Comment by Chiel92** [comment]
I don't see a clear benefit from hiding certain default options, but you already can append to existing definitions. The default definition is in `g:formatdef_clangformat`, so you could use to construct your own definition like this (untested)

```vim
let g:formatdef_my_clangformat = g:formatdef_clangformat . " <here go my other args>"
let g:formatters_cpp = ['my_clangformat']
```
