### ISSUE TITLE
Utilize Autoload Functionality

### ISSUE THREAD

**Issue by sbdchd** [Chiel92/vim-autoformat#106]
It might be beneficial to structure the plugin using an autoload directory.

**Comment by Chiel92** [comment]
Why would this be beneficial?

**Comment by sbdchd** [comment]
Autoloading is supposed to only load the plugin's main code once it is needed, i.e. called by a command such as `:Autoformat`.

Normally, the plugin's code is loaded in full when opening vim.

However, the difference in load time may very well be negligable. ¯\\(°_o)/¯

**Comment by Chiel92** [comment]
There ain't much code to be loaded, the plugin is fairly small. But if you think its worth it, I won't keep you from giving it a try :) I'm inclined to merge in a PR that implements this without compromises.
