### ISSUE TITLE
Rust formatter seems to be broken

### ISSUE THREAD

**Issue by dead10ck** [Chiel92/vim-autoformat#118]
I have this file, which was formatted with `cargo fmt`:

```rust
extern crate kafka;

mod event;

use std::str;
use kafka::consumer::{Consumer, FetchOffset};
use event::Event;

fn main() {
    let mut consumer = Consumer::from_hosts(vec!["docker:9092".to_owned()],
                                            "my-group".to_owned(),
                                            "threatgrid".to_owned())
                           .with_fallback_offset(FetchOffset::Earliest)
                           .create()
                           .unwrap();

    loop {
        for message_set in consumer.poll().unwrap().iter() {
            for m in message_set.messages() {
                // let bytes = Vec::from(m.value);
                // let mut message_string = String::from_utf8(bytes).unwrap();
                let msg_str = str::from_utf8(m.value).unwrap();
                println!("{}", msg_str);
            }
            // consumer.consume_messageset(message_set);
        }
        // consumer.commit_consumed().expect("Failed to commit consumed messages");
    }
}

```

But when I run `:Autoformat` on it, it seems to mess up the indentation on the `Consumer` line:

```rust
fn main() {
    let mut consumer = Consumer::from_hosts(vec!["docker:9092".to_owned()],
    "my-group".to_owned(),
    "threatgrid".to_owned())
        .with_fallback_offset(FetchOffset::Earliest)
        .create()
        .unwrap();
    ...
}
```

**Comment by Chiel92** [comment]
Could you `:set verbose=1` and paste the output of vim-autoformat given in `:messages` here?

**Comment by dead10ck** [comment]
Hmm, this error shows up:

```
Formatter rustfmt has errors: stdin:3:5: 3:10 error: file not found for module `event`
stdin:3 mod event;
            ^~~~~
stdin:3:5: 3:10 help: name the file either event.rs or event/mod.rs inside the directory ""
thread '<main>' panicked at 'Box<Any>', /home/dead10ck/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.23.0/src/parse/mod.rs:98
 Skipping.
Failing config: 'rustfmt'
Definition in 'g:formatdef_rustfmt' was unsuccessful.
No format definitions were successful.
```

So it looks like for some reason it can't find my `event.rs`; but my file layout looks like this:

```
├── Cargo.lock
├── Cargo.toml
├── rustfmt.toml
└── src
    ├── event.rs
    └── main.rs
```
So I don't see a reason it shouldn't be able to find it.

**Comment by Chiel92** [comment]
Hm, and the file you are trying to format is `main.rs` or `event.rs`?

**Comment by dead10ck** [comment]
`main.rs` is the file I posted, yeah

**Comment by Chiel92** [comment]
Well, my first guess would be that it has something to do with current working directories. But why does rustfmt need to load the other file anyway? Formatting code shouldn't really need that, right?

So, what is the working directory of your vim instance when running `:Autoformat`, and what *should* it be in order to format correctly?

**Comment by dead10ck** [comment]
My vim's working directory was `/home/dead10ck/inteldb/live-exporter`, but the error posted above says the directory was `""`. But yeah, I would also think that it shouldn't be necessary for it to find another file anyway, if it's just formatting. I'm not sure how `rustfmt` works though.

**Comment by dead10ck** [comment]
Also, just FYI, I added

```vim
au BufWritePost *.rs silent !cargo fmt
```

to my `.vimrc` and that works. So I'm not sure if there's a difference between doing that and how `vim-autoformat` invokes `rustfmt`.

**Comment by Chiel92** [comment]
Okay, I find that really weird. When running rustfmt from the command line, does it matter from which working directory you run it?

**Comment by dead10ck** [comment]
Just found that this is an open issue with `rustfmt`: https://github.com/rust-lang-nursery/rustfmt/issues/562

So I think the only way to fix it at this point would be to run rustfmt on the files, rather than giving it its input through stdin.

**Comment by Chiel92** [comment]
> So I think the only way to fix it at this point would be to run rustfmt on the files, rather than giving it its input through stdin.

That's not how vim-autoformat works, unfortunately. I don't want to implement it either, because this brings all kinds of issues with it.

Another potential fix could be to pass the file path to rustfmt, similarly to what is done for clang-format. The input is still read from the stdin, but the filepath is used to solve this kind of working directory issues. I'm not sure if rustfmt supports that though.

Anyway, you said that `!cargo fmt` works. But that is weird, since this way rustfmt also gets the input through stdin... (`:h filter`)

**Comment by Chiel92** [comment]
Closing. By all means, continue commenting. Can be reopened if necessary.
