### ISSUE TITLE
js-beautify with config file not working

### ISSUE THREAD

**Issue by hhfei** [Chiel92/vim-autoformat#121]
I want js-beautify point to my config file `~/.jsbeautifyrc`,so I put let `g:formatdef_jsbeautify_javascript = '"js-beautify --config ~/.jsbeautifyrc"'`,but got error:

`Formatter jsbeautify_javascript has errors: Must define at least one file.`

without that config,it works well.

**Comment by hhfei** [comment]
resolve problem by change js-beautify configration.

**Comment by Chiel92** [comment]
By default js-beautify should already find your `~/.jsbeautifyrc` file. So without modifying anything to the vim-autoformat definition, it should work. You have to make sure you are on the latest version of vim-autoformat though. It was implemented last month.
