### ISSUE TITLE
autocmd problem

### ISSUE THREAD

**Issue by dragonxlwang** [Chiel92/vim-autoformat#124]
I am having a issue which strictly speaking, is not resulted from vim-autoformat completely... But I hope that someone can help me out as I have little knowledge about vimL.

I used to have the following to enable autoformat on save:
```
let auto_format_type_list = ['c', 'cpp', 'py']
autocmd BufWritePre * if index(auto_format_type_list, &ft) >= 0 | Autoformat | endif
```
and I also use ``'ntpeters/vim-better-whitespace'``, which strip excessive whitespace on save as well.
```
Plugin 'ntpeters/vim-better-whitespace'
" turn on by default for all filetypes
autocmd BufWritePre * StripWhitespace
```

The problem is for each of them alone they works perfectly. But when put them together in .vimrc, at least one of them won't work depends one who shows up first in the script.

here's what I have after dumping the ``:au BufWritePre``

```
:au bufwritepre
--- Auto-Commands ---
BufWrite
    *         if index(auto_format_type_list, &ft) >= 0 | Autoformat | endif
              StripWhitespace
```

I also noticed that if I use 
```
autocmd BufWritePre * Autoformat
```

Both commands works flawlessly (however it will format check every file which is not what I desire).

So it appears that the problem is resulted from using ``if ... endif `` test there.
---------------------

After playing around for a while I found that by changing the way to autoformat on save using a function call instead using a function call:
```
 autocmd BufWritePre * call Determine_if_auto_format()
 function! Determine_if_auto_format()
   let auto_format_type_list = ['c', 'cpp', 'py']
   if index(auto_format_type_list, &ft) >= 0
     Autoformat
   endif
 endfunction
```
Both of them can works with each other.

Can someone please help me out understanding what's going on here? Thanks!

**Comment by Chiel92** [comment]
First of all, note that vim-autoformat also comes with a RemoveTrailingSpaces command. Check the readme for more info: "When no formatprogram exists (or no formatprogram is installed) for a certain filetype, vim-autoformat falls back by default to indenting, (using vim's auto indent functionality), retabbing and removing trailing whitespace." 
This can be configured to your needs.

About your question, maybe it has something to do with the time of evaluation. In any way, this type of question shouldn't really be asked here. I recommend posting this question on http://stackoverflow.com/ or http://vi.stackexchange.com/

**Comment by dragonxlwang** [comment]
Hi @Chiel92 ,

It seems now clear to me that it is highly likely that there is some problem with vim-autoformat.

Try the following

```
cmd BufWritePre * echom index(auto_format_type_list, &ft) | sleep 2000m |  if index(auto_format_type_list, &ft) >= 0 | Autoformat | endif | echom 'autoformat end'
```

No matter whether it's a c/c++/py file, the part after endif is never executed. However, if change ``Autoformat`` to something like ``sleep 2000m``, I can always get correct (and expected) messages.

Hope that if you have time you can try to fix it. I tried to look into the [code](https://github.com/Chiel92/vim-autoformat/blob/master/plugin/autoformat.vim#L273) and [here](https://github.com/Chiel92/vim-autoformat/blob/master/plugin/autoformat.vim#L65) but I couldn't tell too much.

**Comment by Chiel92** [comment]
>And about the fallback autoformat, because it use indent which sometimes (if not always) gives me surprising result which I don't desire, so in those cases I would rather use a simple way to remove only extra whitespaces.

You can configure that with a few settings, like `let g:autoformat_autoindent = 0`. It's all in the README!

About that other behaviour. I'll look into it when I have time.

**Comment by Chiel92** [comment]
It appears that vim language cannot always deal correctly with commands inside a onliner using these bars `|`. In this case the part after `Autoformat` is interpreted as argument for `Autoformat`, which is of course not the intention, but vim language doesn't know better apparently. You can easily work around these by using `exe`.

```vim
autocmd BufWritePre *.js echom 'hello' | if 1 | exe "Autoformat" | endif | echom 'autoformat end'
```

Still, I think you should use the options I mentioned to configure vim-autoformat the way you want. I just pushed a commit adding bufferlocal variants, such that you can replicate the behaviour you describe by something like 

```vim
autocmd FileType cpp,c,python let b:autoformat_autoindent=0
```

**Comment by dragonxlwang** [comment]
thanks!

**Comment by Chiel92** [comment]
To display trailing whitespace I use https://github.com/tpope/vim-sensible (which does more things than just that :)

**Comment by dragonxlwang** [comment]
nice! :+1:

**Comment by Chiel92** [comment]
PR https://github.com/Chiel92/vim-autoformat/pull/141 now allows the requested behaviour from this issue.
