### ISSUE TITLE
Possible integration with 'equalprg' command

### ISSUE THREAD

**Issue by cmcginty** [Chiel92/vim-autoformat#126]
Vim provides a way to expand the built-in '=' formatting command with 'equalprg' variable. Is there maybe a way that the autoformat plugin could integrate with equalprg or remap the '=' command somehow? 

What are your thoughts on this? Maybe just expanding the install docs might be all that is needed.

**Comment by Chiel92** [comment]
I'm not sure what you mean by 'integrate' :) Could you give an example or something?

Depending on how you define 'integrate', you could say that vim-autoformat already integrates with it, since the "=" command is executed when no formatprg is available.

**Comment by Chiel92** [comment]
Closing. Can be reopened if necessary.
