### ISSUE TITLE
Marks file as changed even when it hasn't

### ISSUE THREAD

**Issue by andrewferrier** [Chiel92/vim-autoformat#128]
Thanks for all your great work on `vim-autoformat`: great job and very useful tool.

One very minor irritation; if I run `:Autoformat` on a file which has already been formatted (in other words it doesn't need any changes, even a byte), it is still marked as changed/dirty in vim. Most other vim manipulation commands don't do this (e.g. `1G=G` would not).

It's not a big deal - more cosmetic than anything - but could be irritating for some workflows, and doesn't clearly show to the user when formatting has been needed, and when it hasn't.

**Comment by Chiel92** [comment]
I agree with this. I suppose we could keep the old text in memory and compare it to the new text before we actually apply it.

**Comment by andrewferrier** [comment]
Yes. Actually, I just did another quick check and if I create a file which is already sorted, for example:

```
a
b
```

... then I run `:'<,'>!sort` on it, the file is not changed (since it's already sorted), but calling out to the external command does automatically mark it as dirty.

So arguably there is a precedent for vim-autoformat's existing behaviour, if you see it as using external commands (which of course it is). That just might not be obvious to everyone ...

Keeping the old text would probably work, but could be a performance issue on large files.

**Comment by Chiel92** [comment]
> Keeping the old text would probably work, but could be a performance issue on large files.

Yes, but I think we can safely assume that formatting work itself on a large file takes more time.

**Comment by andrewferrier** [comment]
True. I wanted to dabble a bit with vimscript, so I'll give this a go if I get time.

**Comment by Chiel92** [comment]
@andrewferrier Would you care to check if https://github.com/Chiel92/vim-autoformat/pull/213 fixes the issue to your satisfaction?

**Comment by andrewferrier** [comment]
Yep, that appears to fix it perfectly. Thanks!
