### ISSUE TITLE
strange formatting issue

### ISSUE THREAD

**Issue by jayceekay** [Chiel92/vim-autoformat#129]
does anyone know why this might happen?

![why](https://cloud.githubusercontent.com/assets/1119866/14685278/fa6addb8-0701-11e6-8891-85d31faf3164.gif)

my `.editorconfig`:
```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

lots of weirdness - the spaces after `'aggregate'` looks like it's trying to align with something else but failing, whitespace is being added to the end of lines rather than stripped:

<img width="442" alt="screen shot 2016-04-20 at 2 15 05 pm" src="https://cloud.githubusercontent.com/assets/1119866/14685425/9a563fde-0702-11e6-84aa-ed87fc241ad2.png">

i realize this may not have to do with autoformatter at all, but was hoping someone could point me in the right direction. i'm using js-beautify v1.6.2 which is installed globally via npm, and AFAIK i haven't overridden any default behavior.

**Comment by Chiel92** [comment]
To check whether this has to do with vim-autoformat, try to reproduce the behaviour on the commandline. If the same behaviour is observed there, the problem is with js-beautify. Otherwise the issue may be with vim-autoformat. Please reopen this issue in that case.
