### ISSUE TITLE
wipes jump list?

### ISSUE THREAD

**Issue by nhooyr** [Chiel92/vim-autoformat#134]
vim-autoformat wipes the entire jump list whenever I use it.

**Comment by Chiel92** [comment]
Thanks for reporting. I will look into it when I have time. This may be related to https://github.com/Chiel92/vim-autoformat/issues/131 and https://github.com/Chiel92/vim-autoformat/issues/128 and https://github.com/Chiel92/vim-autoformat/issues/96

**Comment by vasyapupkin123456** [comment]
Yes, I have this problem too

**Comment by vasyapupkin123456** [comment]
I have this problem too

**Comment by Chiel92** [comment]
It is not a bug. It is a problem inherent to replacing the contents of a buffer with something else. Since we cannot make any assumptions a priori of how the new content relates to the old content, it is not trivially clear how to take positions accross this operation. Some work has to be done.

**Comment by vasyapupkin123456** [comment]
Before replace content save jump list & after replace content restore jump list

**Comment by Chiel92** [comment]
I suppose that might be a workaround that works well for most cases. Wanna give it a try?

**Comment by Chiel92** [comment]
I don't think this is an issue anymore, as I can't seem to reproduce anymore. @nhooyr could you verify?

**Comment by Chiel92** [comment]
Please reopen if this is still an issue.
