### ISSUE TITLE
yapf autoformat for python is not working

### ISSUE THREAD

**Issue by WHQ25** [Chiel92/vim-autoformat#137]
I am using yapf as my format program. yapf did well when I use it in terminal. When I set formatprg to yapf and then use gq{motion} command, the format output is the same with the terminal output which is good. However when I use Autoformat command in vim, the format is really bad. Anyone has the same issue?

**Comment by WHQ25** [comment]
The Autoformat output is the same with autoindent output "gg=G".

**Comment by Chiel92** [comment]
I don't use yapf myself, but a quick try shows me that it's not the same as `gg=G`, but its not pretty either. Anyway, the output is the same as from the cmd line for me. 

The fact that it seems like vim-autoformat is indenting the code might indicate that there is something wrong with the execution of the yapf command, which makes vim-auformat fallback to indenting only. Could you `set verbose=1` and post the messages?

@cmcginty

**Comment by cmcginty** [comment]
Can you verify that YAPF binary file is on the command path available to VIM?

    :echo $PATH

**Comment by WHQ25** [comment]
This is the printing.

Formatter autopep8 has errors: /bin/sh: autopep8: command not found
 Skipping.
Failing config: 'autopep8 - '
Definition in 'g:formatdef_autopep8' was unsuccessful.
Formatter yapf has errors: yapf: "indent_width:4" is not a valid style or file path
 Skipping.
Failing config: 'yapf --style={based_on_style:google,indent_width:4} -l 1-208'
Definition in 'g:formatdef_yapf' was unsuccessful.
No format definitions were successful.
Removing trailing whitespace...
Retabbing...
208 lines indented

**Comment by Chiel92** [comment]
That is interesting, since it works for me. But it also makes sense that a shell might expand these accolades, resulting in invalid arguments.

@WHQ25 @cmcginty what OSs are you using?

**Comment by WHQ25** [comment]
I am using mac  @Chiel92

**Comment by cmcginty** [comment]
That explains it. I'm running Mint Linux 17.3
