### ISSUE TITLE
Formatting HTML wipes buffer

### ISSUE THREAD

**Issue by tuoppimas** [Chiel92/vim-autoformat#140]
The autoformatting works great for all other types of code, but when I format HTML code, the buffer contents are deleted, and I must undo to get them back. Right now I am using another plugin to format HTML code, but it would be great to get this plugin to work.

**Comment by Chiel92** [comment]
Thanks for creating an issue in this repo. Could you specify the formatter that you use, together with the messages output after having `:set verbose=1`?

**Comment by tuoppimas** [comment]
I am trying to use html-beautify.
If I run it with verbose:
Definition in 'g:formatdef_htmlbeautify' was successful.  

And the buffer contents are lost.

**Comment by tuoppimas** [comment]
Sorry for wasting your time. The problem is not with the plugin, but my html-beautify installation which returns nothing when it is run.  I have it now configured to use html-tidy and everything works.
Thank you.
