### ISSUE TITLE
Here documents in bash script

### ISSUE THREAD

**Issue by guiwp** [Chiel92/vim-autoformat#142]
When I use "Autoformat" the formatter for bash scripts do not handle here documents. Suppose we have one block like:

```
if true;then
cat <<EOF
...
EOF
fi
```

The EOF bareword is indented.

**Comment by Chiel92** [comment]
That is because vim's indent file does it that way. Report this issue to the maintainer of the corresponding indent file. I guess in your case you should have a look in vim/indent/sh.vim.
