### ISSUE TITLE
JSX support by default

### ISSUE THREAD

**Issue by ifokeev** [Chiel92/vim-autoformat#146]
js-beautify supports JSX with -X argument
```  -X, --e4x                         Pass E4X xml literals through untouched```

I think it should be supported by default already

**Comment by Chiel92** [comment]
Is there a specific version in which this was introduced?

**Comment by ifokeev** [comment]
I'm wrong. ES6 initial supported since js-beautify 1.5.2, https://github.com/beautify-web/js-beautify/milestone/9.
But -X flag adds XML literals support (like JSX). 
Without this flag it will beautify like this:
```
return <div {...props
    } > < /div>;
```

instead of

```
return <div {...props}></div>;
```

**Comment by ifokeev** [comment]
Correct PR: https://github.com/Chiel92/vim-autoformat/pull/148

**Comment by Chiel92** [comment]
Hm, I fail to see the difference between #145 and #148. Did you intend #148 to do something different?

**Comment by ifokeev** [comment]
>Did you intend #148 to do something different?
Just change the commit. It was incorrect.

**Comment by Chiel92** [comment]
I see. This looks good to me then.
