### ISSUE TITLE
No warning when formating fails with RustFmt

### ISSUE THREAD

**Issue by IGI-111** [Chiel92/vim-autoformat#149]
RustFmt can fail behind the scenes when docstrings are too long
```
Rustfmt failed at test.rs:1: line exceeded maximum length (sorry)
```
but this isn't reported and so this code:

```rust
/// a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long docstring
pub fn main() {
let badly;
let indented;
            let code;
            let a_line_that_could_probably_be_broken_in_two = "but won't because rustfmt isn't actually parsing it";
}
```

results in

```rust
/// a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long docstring
pub fn main() {
    let badly;
    let indented;
    let code;
    let a_line_that_could_probably_be_broken_in_two = "but won't because rustfmt isn't actually parsing it";
}
```

when 

```rust
pub fn main() {
let badly;
let indented;
            let code;
            let a_line_will_actually_be_broken_down = "and actually will because rustfmt is not bailing without any warning";
}


```

results in

```rust
pub fn main() {
    let badly;
    let indented;
    let code;
    let a_line_will_actually_be_broken_down = "and actually will because rustfmt is not bailing \
                                               without any warning";
}
```

which is surprising behavior. Well at least it caught me off guard.

Shouldn't those errors be reported to the user somehow?
Defaulting to the vim indentation when RustFmt isn't installed is nice, but when it is and it's reporting errors, I'd love to see them somehow.

**Comment by Chiel92** [comment]
You can bring these messages to front by setting `:set verbose=1` before running the command. This will make vim-autoformat spawn messages about things going wrong.

If you are annoying by vims indentation behaviour, you could `let g:autoformat_autoindent = 0`.

Anyway, formatter programs shouldn't fail on broken code. 

However, I still can see a potential problem here. Would you mind reporting the return code of the rustfmt process when it gives this error?

**Comment by IGI-111** [comment]
```
~ ❯ rustfmt test.rs
Rustfmt failed at test.rs:1: line exceeded maximum length (sorry)

~ ❯ echo "$?"
3
```

**Comment by Chiel92** [comment]
Ok, the strictly positive return code suggests that rustfmt really fails.
Is this a known bug in rustfmt? I bet it is: https://github.com/rust-lang-nursery/rustfmt/issues/1080
To get this fixed you should submit a patch for rustfmt.
