### ISSUE TITLE
rustfmt does not work

### ISSUE THREAD

**Issue by chenhouwu** [Chiel92/vim-autoformat#154]
when format a `rust` file, I got the following error

```
Formatter rustfmt has errors: error: file not found for module `apple`
 --> stdin:1:9
  |
1 | pub mod apple;
  |         ^^^^^^^^
  |
  = help: name the file either apple.rs or apple/mod.rs inside the directory ""
 Skipping.
Failing config: 'rustfmt'
Definition in 'g:formatdef_rustfmt' was unsuccessful.
No format definitions were successful.
Removing trailing whitespace...
Retabbing...
24 lines indented

```
But `rust.vim` can work well by the `:RustFmt` command.
Of course, `cargo fmt` also works well.

I have the following file structure:

```
project/src/
├── api
│   ├── high
│   │   ├── mod.rs
│   │   ├── apple.rs
│   │   └── orange.rs
```
When I format the `mod.rs` file, it can't find the `apple.rs` file.
So there might be some issue with `pwd` when invoking vim-autoformat?

**Comment by Chiel92** [comment]
Duplicate: https://github.com/Chiel92/vim-autoformat/issues/118
