### ISSUE TITLE
Help Me With This Autoformat Feature

### ISSUE THREAD

**Issue by huangyingw** [Chiel92/vim-autoformat#155]
I want to implement this feature: to search up from my current file, to the root directory of my git directory, to see whether there is a file called .astylerc.
    If yes, will use the .astylerc to format my java codes.
    But somehow, it does not work. Could you help me to take a look, or give me some help ?
    Great thanks.

   When I try to format a java file, and I put an .astylerc file under my Git root folder, it tell me this error:

Error detected while processing function <SNR>75_TryAllFormatters:
line   38:
E121: Undefined variable: Users
85 lines indented

snippets in defaults.vim
=================================================================================
" Java
if !exists('g:formatdef_astyle_java')
    let b:gitRoot = Find_in_parent(".git/config",Windowdir(),$HOME)
    if filereadable(b:gitRoot . "/" . '.astylerc' )
        let g:formatdef_astyle_java = '"astyle --mode=java --options="' . b:gitRoot . "/" . '.astylerc'
    endif
endif
    
=================================================================================

Find_in_parent and Windowdir are defined in .vimrc file
=================================================================================
"
"==
" Find_in_parent
" find the file argument and returns the path to it.
" Starting with the current working dir, it walks up the parent folders
" until it finds the file, or it hits the stop dir.
" If it doesn't find it, it returns "Nothing"
function! Find_in_parent(fln,flsrt,flstp)
  let here = a:flsrt
  while ( strlen( here) > 0 )
    if filereadable( here . "/" . a:fln )
      return here
    endif
    let fr = match(here, "/[^/]*$")
    if fr == -1
      break
    endif
    let here = strpart(here, 0, fr)
    if here == a:flstp
      break
    endif
  endwhile
  return "/"
endfunc

"==
" windowdir
"  Gets the directory for the file in the current window
"  Or the current working dir if there isn't one for the window.
"  Use tr to allow that other OS paths, too
function! Windowdir()
  if winbufnr(0) == -1
    let unislash = getcwd()
  else 
    let unislash = fnamemodify(bufname(winbufnr(0)), ':p:h')
  endif
  return tr(unislash, '\', '/')
endfunc
=================================================================================

**Comment by jpmv27** [comment]
Can you elaborate on what is happening vs. what you expect?

Off the top of my head, shouldn't --options point to gitRoot.'/.astylerc'?

**Comment by huangyingw** [comment]
@jpmv27 yes, you are correct, update my comment.
When I try to format a java file, and I put an .astylerc file under my Git root folder, it tell me this error:

Error detected while processing function 75_TryAllFormatters:
line 38:
E121: Undefined variable: Users
85 lines indented

**Comment by jpmv27** [comment]
I think your problem may be "$HOME". Do you not perhaps want "expand('$HOME')" instead?

**Comment by huangyingw** [comment]
@jpmv27 , when I change to 
    let b:gitRoot = Find_in_parent(".git/config",Windowdir(),expand($HOME))
I got this error:
Error detected while processing function <SNR>75_TryAllFormatters:
line   32:
No format definition found in 'g:formatdef_astyle_java'.

**Comment by jpmv27** [comment]
Looks like my last suggestion was a bust, now it's not setting g:formatdef_astyle_java at all.
Are you on Windows or Unix?
What value is g:formatdef_astyle_java set to?

**Comment by huangyingw** [comment]
@jpmv27 
Great thanks, I found the reason
an extra " around options caused my problem.
     It should be 
        let g:formatdef_astyle_java = '"astyle --mode=java --options=' . b:gitRoot . "/" . '.astylerc"'
    instead of
        let g:formatdef_astyle_java = '"astyle --mode=java --options="' . b:gitRoot . "/" . '.astylerc'

**Comment by Chiel92** [comment]
:+1:
