### ISSUE TITLE
Latex indentation takes a long time

### ISSUE THREAD

**Issue by BigfootN** [Chiel92/vim-autoformat#165]
Hello,

I noticed that when I worked on latex documents it took longer and longer to indent. I often save my document. The first time I make a change it takes absolutely no time, but after saving several times, it takes several seconds (~10) to save/indent my document.

I enabled the autoformatting when saving.

Thank you very much in advance.

**Comment by Chiel92** [comment]
Is this issue closed intentionally?

**Comment by BigfootN** [comment]
Sorry, yes, I finally found the solution. Unfortunately, I was unable to delete the issue.
But thank you for answering.
