### ISSUE TITLE
python pep8 linelength and trailing whitespaces

### ISSUE THREAD

**Issue by ocehugo** [Chiel92/vim-autoformat#166]
Hi,

1)there is any easy way to setup vim-autoformat or yapf to follow pep8 guidelines regarding linelength?

The problem is: Comments/docstrings should be limited to 72 chars, while code should be limited to 79.  Current default limit everything to 79. Any quick hack to pose the 72 limits only for comments/docstrings? 

Not verse in vimscript so any help would be nice.

2) Currently auto-format/yapf do not remove trailing whitespaces in comments/docstrings. I was using auto-format to make docstrings looks nice but some manual editing in some of them create white trailing spaces that are warned by pep8 but not corrected by yapf/autoformat. I believe this is a limitation of yapf!?

Cheers

**Comment by Chiel92** [comment]
Both issues mainly have to do with the specific formatters themselves. You should check out their documentation or post an issue on their mailinglist/repository.
