### ISSUE TITLE
XML text deleted when not correctly formated

### ISSUE THREAD

**Issue by BigfootN** [Chiel92/vim-autoformat#172]
Hello,

I have a problem when editing xml files. When saving xml files not starting with '<', the whole text is deleted. So when opening a file not starting with '<' it's like I haven't written anything.

Here are my options:
```
autocmd FileType vim,tex,xml let b:autoformat_autoindent=0
au BufWrite * :Autoformat
```

Thank you very much in advance

**Comment by Chiel92** [comment]
Please provide some extra info by setting vim-autoformat in verbose-mode and reporting back.

```vim
let g:autoformat_verbosemode=1
" OR:
let verbose=1
```

To read all messages in a vim session type `:messages`.  Since one cannot always easily copy
the contents of messages (e.g. for posting it in an issue), vim-autoformats command `:PutMessages` may
help. It puts the messages in the current buffer, allowing you to do whatever you want.

**Comment by BigfootN** [comment]
Thank you for your answer. Unfortunately it doesn't seem to be anything, it only shows:

```
<name of file> 1L, 1C
<name of file> 1L, 1C written
```

Thank you again very much in advance

**Comment by Chiel92** [comment]
That means that `:Autoformat` isn't executed! What happens when you remove the `au BufWrite * :Autoformat` and trigger manually?

**Comment by BigfootN** [comment]
If I remove the `au BufWrite * :Autoformat` and trigger `:Autoformat` manually, the text also disappears.

Thank you very much again in advance

**Comment by Chiel92** [comment]
And still no output in `:messages` after setting `:set verbose=1`?

**Comment by BigfootN** [comment]
Oh, I feel really stupid sorry, I wrote `let verbose=1` instead of `set verbose=1`, now I have `cannot find in runtimepath : "indent/qf.vim"`
Really sorry again and thank you for your help

**Comment by Chiel92** [comment]
Sounds like your installation is broken or your vimrc is bogus.
Still I would expect more output in `:messages` than just that line.
Try

```
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
```

and see what happens...

**Comment by BigfootN** [comment]
Thank you it works ! Even though indentation doesn't work, which is quite normal with these options

Thank you very much again

**Comment by Chiel92** [comment]
Well I suppose it doesn't remove anything, but doesn't format anything either.
Anyway, these problems sound like they have to do with something else. You probably have other problematic plugins or configuration. If you still run into trouble, and you think vim-autoformat is to blame, try testing in a clean vim environment first, i.e. without other plugins and any custom configuration.

**Comment by BigfootN** [comment]
Thank you again ! Just so you know, before creating this issue I tested it without any configuration or plugins: `nvim -u NONE`, and it in fact worked.

**Comment by BigfootN** [comment]
I tried with a very simple vimrc:

```
call plug#begin('~/.vim/plugged')

Plug 'Chiel92/vim-autoformat'

call plug#end()
```

And when I edit a simple xml file, with this text in it:
```
test>
body
</test>
```
and do a `:Autoformat` the whole text just disappears.

With `set verbose=1` the only message I get is `Definition in 'g:formatdef_tidy_xml' was successfull`

Thank you very much again

**Comment by Chiel92** [comment]
Try running the command `tidy` from the command line manually, and post the output including the return code of the process.

**Comment by BigfootN** [comment]
After spending some time with tidy it seems that it is it's purpose. I haven't found any option counteracting this behaviour.

Thank you very much again for all precious your help and patience

**Comment by Chiel92** [comment]
If tidy would have a return code > 0 upon failure like that, vim-autoformat would recognize that. If you think that is a good idea to have in tidy, you could try contacting the tidy devs with this feature.

**Comment by niftylettuce** [comment]
I have the same error as above `not found in 'runtimepath': "indent/qf.vim"`.  I basically added a trailing comma (a typo) to a `package.json` file and saved it.  It ran the `xo` formatter.
