### ISSUE TITLE
format vue file using defined html, css, js formaters.

### ISSUE THREAD

**Issue by hatelove85911** [Chiel92/vim-autoformat#173]
I'm learning [vue.js](https://github.com/vuejs/vue) framework, a vue file will contain three sections:

- template
- script
- style 

Inside template section, it's html code. 
Inside script section, js code is written. 
And we put css code inside style section.
It's just like a html file.

What I want is to format each of the section using the formaters I have defined for each file type.
So I would like to use html-beautify to format the template section.
standard to format the script section.
css-beautify to format the style section.

**Comment by Chiel92** [comment]
For this to work there needs to be a single formatter that can do this. I don't write web code myself, but I would guess there is something out there that does this. Doesn't html-beautify already does this?

Anyhow, if that is not the case, you should create this issue in the js-beautify repository. It's more appropriate there, as there is no practical way we can implement such functionality in vim-autoformat.
