### ISSUE TITLE
YAPF formatting issue

### ISSUE THREAD

**Issue by dfee** [Chiel92/vim-autoformat#175]
I'm using nvim 0.1.7, the latest vim-autoformat, and yapf 0.13.2. a minimal VIM file:
```
call plug#begin()
Plug 'Chiel92/vim-autoformat'
call plug#end()

noremap <F3> :Autoformat<CR>
```

I run `:Autoformat` on my test.py file which looks like:
```
x = {  'a':37,'b':42,

'c':927}

y = 'hello ''world'
z = 'hello '+'world'
a = 'hello {}'.format('world')
class foo  (     object  ):
  def f    (self   ):
    return       37*-+2
  def g(self, x,y=42):
      return y
def f  (   a ) :
  return      37+-+a[42-x :  y**3]
```

and get:
```
x = {'a': 37, 'b': 42,

     'c': 927}

y = 'hello ''world'
z = 'hello ' + 'world'
a = 'hello {}'.format('world')


class foo  (object):

    def f(self):
        return 37 * -+2

    def g(self, x, y=42):
        return y


def f(a):
    return 37 + -+a[42 - x:  y**3]
```

But, I expect to get (and do get when I run yapf directly on the file from the command line):
```
x = {'a': 37, 'b': 42, 'c': 927}

y = 'hello ' 'world'
z = 'hello ' + 'world'
a = 'hello {}'.format('world')


class foo(object):
    def f(self):
        return 37 * -+2

    def g(self, x, y=42):
        return y


def f(a):
    return 37 + -+a[42 - x:y**3]
```

A few other points:
* despite having a .style.yapf file in my project directory, those settings are not picked up by yapf-autoformatter (they are picked up by `yapf test.py`).
* The only message after running `:Autoformat` is: `Definition in 'g:formatdef_autopep8' was successful.`

I noticed another issue recently posted that might be related (though that user had a problem with autopep8 being run). https://github.com/Chiel92/vim-autoformat/issues/168

**Comment by Chiel92** [comment]
> The only message after running :Autoformat is: Definition in 'g:formatdef_autopep8' was successful.

That is a major hint. Apparently you have autopep8 installed as well as yapf, so vim-autoformat has to choose. Arbitrarily it uses the first formatter that works, which appears to be autopep8. To tell vim-autoformat that yapf has a higher priority, redefine the list of python formatters in your vimrc like

```
let g:formatters_python = ['yapf', 'autopep8']
```

or else make vim-autoformat consider just yapf (and disregard autopep8 completely)

```
let g:formatters_python = ['yapf']
```

**Comment by dfee** [comment]
Wow. That's like looking at 2 + 2 = 5 and not seeing the problem. I appreciate your quick insight. Case closed :)

**Comment by dfee** [comment]
I spoke too soon. This is now formatting the code as expected, but it's still not taking account options in my `.style.yapf` (whereas running yapf from the command line does).

**Comment by Chiel92** [comment]
I'm not a yapf user myself, but fortunately figuring this out isn't hard.

After running the formatter, you can view the formatter command used by typing `:echo b:formatprg`.
Does this match the command you use on the command line?
1. If not, than that maybe the source of the difference in behavior.
  You could propose a modification on the default definition, which would take the style file into account.
2. If it matches, maybe the working directory can be a source of the behavioral difference?

**Comment by Chiel92** [comment]
Any updates on this?

**Comment by dfee** [comment]
Sorry, I must not have seen the previous notification. Yep, all good. Thanks @Chiel92
