### ISSUE TITLE
Is it any method to check current file was be formated?

### ISSUE THREAD

**Issue by qwIvan** [Chiel92/vim-autoformat#179]
I want to display a tips went I save file.

**Comment by Chiel92** [comment]
I'm sorry, I don't understand what you're asking. What is that you want to display when you save a file? I don't know what "tips" means in this context.

**Comment by qwIvan** [comment]
sorry, I means that whether the file can be able to formatting, whether the file is already been formatted to the best.

**Comment by Chiel92** [comment]
No, such function does not exist yet. If want/need it, you need to write it yourself.

**Comment by qwIvan** [comment]
thx
