### ISSUE TITLE
what if I want autoformat the code locally?

### ISSUE THREAD

**Issue by 3xp10it** [Chiel92/vim-autoformat#180]
I have a python script with around 10000 lines,what if I want to autoformat my script from line4000 to line4100?
Can you help me?
Can I use :4000,4100Autoformat ?

**Comment by Chiel92** [comment]
Something like that should work if the formatter you use supports ranged formatting. Autopep8 supports it. Have you tried it?

**Comment by 3xp10it** [comment]
Hi, @Chiel92  I browsed <a href="https://pypi.python.org/pypi/autopep8">autopep8</a> site,but can not find the usage about `ranged formatting`,can you show me how?
