### ISSUE TITLE
Allow providing a default that is only used in case .clang-format is not provided

### ISSUE THREAD

**Issue by svenstaro** [Chiel92/vim-autoformat#181]
I would like to have a setup where I define a personal style that I prefer for clang autoformatting that will be used in case a project doesn't define its own .clang-format. If a project does define that style, I would like my own style to be overwritten with the project's style. I think that way of working actually makes a lot of sense.

Currently, vim-autoformat does not support that. In case `let g:formatdef_clangformat` is defined, the .clang-format is skipped entirely.

What do you think? I could make a patch for this.

**Comment by Chiel92** [comment]
You can either make sure there is another, more toplevel, `.clang-format` file with your own rules, or define your own formatter definition.
If you look at the code of the current clang format definition, you can easily tweak that and create your own.

```
let s:configfile_def = "'clang-format -lines='.a:firstline.':'.a:lastline.' --assume-filename=\"'.expand('%:p').'\" -style=file'"
let s:noconfigfile_def = "'clang-format -lines='.a:firstline.':'.a:lastline.' --assume-filename=\"'.expand('%:p').'\" -style=\"{BasedOnStyle: WebKit, AlignTrailingComments: true, '.(&textwidth ? 'ColumnLimit: '.&textwidth.', ' : '').(&expandtab ? 'UseTab: Never, IndentWidth: '.shiftwidth() : 'UseTab: Always').'}\"'"
let g:formatdef_clangformat = "g:ClangFormatConfigFileExists() ? (" . s:configfile_def . ") : (" . s:noconfigfile_def . ")"
```
