### ISSUE TITLE
Doesn't reports when eslint errors

### ISSUE THREAD

**Issue by zubieta** [Chiel92/vim-autoformat#182]
_vim-autoformat_ doesn't report anything if _eslint_ fails to run. One example is when the _.eslintrc.json_ specifies a dependency that hasn't been installed.

When you run `node_modules/.bin/eslint -c .eslintrc.json --fix input.js` from the terminal you get the following error if _babel-eslint_ hasn't been installed:
```
Cannot find module 'babel-eslint'
    Error: Cannot find module 'babel-eslint'
    at ModuleResolver.resolve (/home/user/project/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at Object.load (/home/user/project/node_modules/eslint/lib/config/config-file.js:554:42)
    at loadConfig (/home/user/project/node_modules/eslint/lib/config.js:63:33)
    at new Config (/home/user/project/node_modules/eslint/lib/config.js:231:42)
    at CLIEngine.executeOnFiles (/home/user/project/node_modules/eslint/lib/cli-engine.js:590:28)
    at Object.execute (/home/user/project/node_modules/eslint/lib/cli.js:171:107)
    at Object.<anonymous> (/home/user/project/node_modules/eslint/bin/eslint.js:74:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
```
and the command exits with an error code of 1.

But there is no report of such error when trying to auto-format from within vim. So it becomes really hard to actually know that something is missing.

BTW, awesome software. Thanks for all your work!

**Comment by zubieta** [comment]
I found one issue. There is a missing semicolon after the exit_code assignation.

```diff
diff --git a/plugin/defaults.vim b/plugin/defaults.vim
index 4085f02..1a1e553 100644
--- a/plugin/defaults.vim
+++ b/plugin/defaults.vim
@@ -188,7 +188,7 @@ if !exists('g:formatdef_eslint_local')
                let l:eslint_js_tmp_file = fnameescape(tempname().".js")
                let content = getline('1', '$')
                call writefile(content, l:eslint_js_tmp_file)
-               return l:prog." -c ".l:cfg." --fix ".l:eslint_js_tmp_file." 1> /dev/null; exit_code=$?
+               return l:prog." -c ".l:cfg." --fix ".l:eslint_js_tmp_file." 1> /dev/null; exit_code=$?;
                                         \ cat ".l:eslint_js_tmp_file."; rm -f ".l:eslint_js_tmp_file."; exit $exit_code"
        endfunction
        let g:formatdef_eslint_local = "g:BuildESLintLocalCmd()"
```

I still doesn't receive any warning from vim-autoformat when this fails. But `exit_code` now correctly matches _eslint_'s exit code.

**Comment by Chiel92** [comment]
@theanimal666 Could you have a look at this?

**Comment by theanimal666** [comment]
@Chiel92 @zubieta yes i'll have a look at that after my easter holidays.

**Comment by theanimal666** [comment]
i had a look at it and the main problem i see is that eslint --fix returns a non-zero exit code in two cases:
a) like in your example, when some config is missing or similar and it aborts
b) when the --fix run in finished corrected some but not all errors
and it returns 1 in both situations.
so i'm not sure if it is really a good idea to show it failing as (from my experience) it fixes mosr isses and the rest can easily be done manually.

A good solution i can think of would be to poulate the quickfix window with he errors but i have no idea how to do that ;)

**Comment by zubieta** [comment]
I don't know if it is a valid issue and I haven't used JS in a long time now, so I'll close the issue.
