### ISSUE TITLE
Json Does Not Format According to `ShiftWidth`

### ISSUE THREAD

**Issue by springcold** [Chiel92/vim-autoformat#188]
As title.

I have tried to run it with only vim-autoformat plugin and the following settings
Expected: Format to 2 space
Got: Format to 4 space
```
set shell=/bin/bash

" Set Neovim's Python
let g:python_host_prog='/usr/bin/python2'
let g:python3_host_prog='/usr/bin/python3'

set runtimepath+=/usr/local/base/dein.vim/

if dein#load_state("~/.base/install/dein.plugin")
  call dein#begin("~/.base/install/dein.plugin")
  call dein#add("Chiel92/vim-autoformat")
  call dein#end()
  call dein#save_state()
endif

set ft=json
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
```
However, works as expected when I `set ft=<others>`

And my vim..
```
NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/build/config -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/src -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-RxRN0j/neovim-0.1.7ubuntu1+git201702271935+3165+23~ubuntu16.04.1/build/include
Compiled by root@lcy01-05

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by Chiel92** [comment]
Could you post the output of verbose mode? (https://github.com/Chiel92/vim-autoformat#it-doesnt-work)

In this case it would also help to report the contents of `b:formatprg` after running the formatter.

**Comment by peter50216** [comment]
Just encounter the same issue.
It seems that js-beautify had changed the command line arguments (https://github.com/beautify-web/js-beautify/blob/master/python/jsbeautifier/__init__.py#L134-L167), so the '-f' flag now means something completely different.
Set `let g:formatdef_jsbeautify_json = '"js-beautify -i -".(&expandtab ? "s ".shiftwidth() : "t")'` in my vimrc works for me.

**Comment by Chiel92** [comment]
Does this then also affect the other jsbeautify based formatters? Or just the Json formatter.

**Comment by peter50216** [comment]
It seems that the javascript-based js-beautify (https://github.com/beautify-web/js-beautify/blob/master/js/lib/cli.js#L160) and the python-based js-beautify have different command line arguments.
The default value works for javascript-based js-beautify for me.

**Comment by Chiel92** [comment]
Yes, they always have been different afaik. Vim-autoformat should try them both, and use whichever works. If this doesn't work, please report some debug info.

**Comment by springcold** [comment]
This is what is outputted on the verbose
```
Using python 3 code...
Definition in 'g:formatdef_jsbeautify_json' was successful.
js-beautify -f - -s 2
```
seems like the extra `-` is causing the problem, adding the following configuration works
```
let g:formatdef_jsbeautify_json = '"js-beautify -f -".(&expandtab ? "s ".shiftwidth() : "t")'
```

**Comment by springcold** [comment]
I think `-` will terminate flag input and switch to standard input that's why it is not registered.
My take is, all the formatter that has `-` before flags will have such problems, listing:
```
plugin/defaults.vim
143:        let g:formatdef_jsbeautify_javascript = '"js-beautify -X -f - -".(&expandtab ? "s ".shiftwidth() : "t").(&textwidth ? " -w ".&textwidth : "")'
224:        let g:formatdef_jsbeautify_json = '"js-beautify -f - -".(&expandtab ? "s ".shiftwidth() : "t")'
242:    let g:formatdef_htmlbeautify = '"html-beautify -f - -".(&expandtab ? "s ".shiftwidth() : "t")'
292:    let g:formatdef_cssbeautify = '"css-beautify -f - -s ".shiftwidth()'
```

**Comment by Chiel92** [comment]
> seems like the extra - is causing the problem, adding the following configuration works
> `let g:formatdef_jsbeautify_json = '"js-beautify -f -".(&expandtab ? "s ".shiftwidth() : "t")'`

That doesn't make sense to me. Now nothing is passed to the `-f` flag, right? It should receive a file, or `-` for stdin.

```
$ js-beautify --help
js-beautify.js@1.6.2

CLI Options:
  -f, --file       Input file(s) (Pass '-' for stdin)
```

> I think - will terminate flag input and switch to standard input that's why it is not registered.

If that is true, then maybe swapping the arguments will help?
`let g:formatdef_jsbeautify_json = '"js-beautify ".(&expandtab ? "s ".shiftwidth() : "t")." -f -"'`

**Comment by Chiel92** [comment]
Also, for me, setting shiftwidth to 2 has the desired effect. Version: js-beautify.js@1.6.2

**Comment by peter50216** [comment]
To my understanding, both the python and javascript version of the jsbeautify have exact same name.
If the user have only the python version installed, but not the javascript version, autoformat would try to use g:formatdef_jsbeautify_json before g:formatdef_pyjsbeautify_json, but the first one would succeed (with wrong output).

**Comment by peter50216** [comment]
So the easy fix would be add this to doc that the user should disable g:formatdef_jsbeautify_json if only python version is installed, or have some detection code to find out whether the "js-beautify" on the system is javascript version or python version...

**Comment by springcold** [comment]
@peter50216 is totally right, I am on python version:
```
Usage: jsbeautifier.py [options] <infile>

    <infile> can be "-", which means stdin.
    <outfile> defaults to stdout

Input options:

 -i,  --stdin                      Read input from stdin
```

stdin has some difference there

**Comment by springcold** [comment]
I tried without stdin and it worked...

Now.. if `let g:formatdef_jsbeautify_json = '"js-beautify -".(&expandtab ? "s ".shiftwidth() : "t")'` works, wouldn't it unnecessary to add it?

I tried to select in visual mode, wanting to parse parts of the document. However, even with stdin, it still parses the entire document, should this be the expected result?

**Comment by Chiel92** [comment]
Yes, and just adding `-` without flag seems to work too.

I pushed a proposed fix on branch `merge_py_js_jsbeautify_definitions`. Could you both check it out and see if it works for you?

**Comment by peter50216** [comment]
Yes it works for me.

**Comment by springcold** [comment]
Works for me too =)

**Comment by Chiel92** [comment]
Merged!
