### ISSUE TITLE
Provide documentation how to use it with local installed 'eslint'

### ISSUE THREAD

**Issue by alex-shamshurin** [Chiel92/vim-autoformat#190]
I cannot get it work.

**Comment by Chiel92** [comment]
From the readme:

>The linter is then installed locally at node_modules/.bin/eslint When running formatter vim will walk up from the current file to search for such local installation and a ESLint configuration file (either .eslintrc or eslintrc.json). When both are found eslint is executed with the --fix argument. Currently only working on *nix like OS (Linux, MacOS etc.) requires OS to provide sh like shell syntax

Doesn't this fall under your definition of documentation?

**Comment by alex-shamshurin** [comment]
No, I just couldn't make it work with local eslint. Could you give an example?

**Comment by Chiel92** [comment]
No I'm afraid not. I don't know what you mean by "an example", and I don't use eslint myself. And without any further information from your side about what does not work, I can't help you any further. Closed until more information is given.

**Comment by alex-shamshurin** [comment]
```
" Formatting
let g:formatdef_my_custom_js='"./node-modules/.bin/eslint --fix"'
let g:formatters_javascript = ['my_custom_js']
let g:formatters_jsx = ['my_custom_js']
let g:formatters_javascript_jsx = ['my_custom_js']
let g:autoformat_verbosemode = 1

```

I cannot get it work. Question is very simple - how to use it..

**Comment by Chiel92** [comment]
You don't need that vim script. Just opening vim and runing `:Autoformat` should work.
