### ISSUE TITLE
Support prettier, prettier-standard, prettier-eslint for JS

### ISSUE THREAD

**Issue by alex-shamshurin** [Chiel92/vim-autoformat#191]

**Comment by Chiel92** [comment]
What does this mean?

**Comment by alex-shamshurin** [comment]
This means support for best Javascript code formatters. https://github.com/prettier/prettier

**Comment by Chiel92** [comment]
Well, what is best remains subjective, but pull requests are welcome.
That said, I think we already support prettier, via the plugin https://github.com/prettier/eslint-plugin-prettier

**Comment by alex-shamshurin** [comment]
I think it's a different approach, I'd like to have native support. Unfortunately I do no know vim script at all to make a PR. 

> Well, what is best remains subjective

I think it one of the best, I tried all others.
