### ISSUE TITLE
Custom functions/hooks executed before and after autoformat

### ISSUE THREAD

**Issue by MedicineYeh** [Chiel92/vim-autoformat#194]
As discussed online with many threads and this #64 , clang-format cannot do `#pragma omp for` properly. I found the perfect solution and can also be generalized to do more. The concept is to replace `#pragma omp ...` to a comment before the formatting and replace the `//#pragma omp ...` back after the formatting.
The concept can be demo in bash:
``` bash
# Replace "#pragma omp" by "//#pragma omp"
sed -i 's/#pragma omp/\/\/#pragma omp/g' ./main.c
# Do format
clang-format ./main.c
# Replace "// *#pragma omp" by "#pragma omp"
sed -i 's/\/\/ *#pragma omp/#pragma omp/g' ./main.c
```
or vim script:
``` vim
command! -nargs=? -range=% -complete=filetype -bar MAutoformat
            \ let mm_winview=winsaveview() |
            \ <line1>,<line2>s/#pragma omp/\/\/#pragma omp/e |
            \ <line1>,<line2>s/#pragma simd/\/\/#pragma simd/e |
            \ <line1>,<line2> Autoformat |
            \ <line1>,<line2>s/\/\/ *#pragma simd/#pragma simd/e |
            \ <line1>,<line2>s/\/\/ *#pragma omp/#pragma omp/e |
            \ call winrestview(mm_winview)
```

I use this vim script and it works. However..... I really don't know how to write a vim function and loop that make this ugly code better. I propose to have this ability to do something before and after Autoformat. I'm sorry that due to my ability, I cannot provide a PR. I hope someone can help to do that.

More descriptions are available here:
https://medicineyeh.wordpress.com/2017/07/13/clang-format-with-pragma/#more-1846

**Comment by Chiel92** [comment]
Alternatively you could consider that bash script a formatprogram, and create a format definition for that. Sounds easier to me.

**Comment by MedicineYeh** [comment]
Yeah, that is an alternative solution for this as well. I just try to propose a new idea here. The load seems to be not easy. Maybe we should stick with the script solution which is also more extensible.
