### ISSUE TITLE
Vim has no support for python when formatting code

### ISSUE THREAD

**Issue by ankitrg** [Chiel92/vim-autoformat#195]
I am getting this warning, I couldn't find anything in the doc about this warning and how to fix it.
https://github.com/Chiel92/vim-autoformat/blob/master/plugin/autoformat.vim#L116

**Comment by Chiel92** [comment]
Isn't the error self-explanatory? Your vim distribution needs python support in order to use vim-autoformatter. It says in the docs right here: https://github.com/Chiel92/vim-autoformat#how-to-install
