### ISSUE TITLE
XML tidy breaks utf8 umlauts (on macOS)

### ISSUE THREAD

**Issue by stroebjo** [Chiel92/vim-autoformat#196]
`tidy` seems to break umlauts in an XML file wich is utf8. `ä` gets `&#195;&#164;`. At least on macOS.

Adding the `-utf8` option to to the tidy call fixes this. But this can't be applied in general I think?

Sample XML:

```
<catalog> <book id="bk101"> <author>Gambardella, Matthew</author> <title>XML Developer's Guide</title> <genre>Computer</genre> <price>44.95</price> <publish_date>2000-10-01</publish_date> <description>An in-depth look at creating applications with XML. Alos a lot of umlauts for testing äöü.</description> </book></catalog>
```

**Comment by Chiel92** [comment]
What about `raw`?

**Comment by stroebjo** [comment]
Yes, I just tested it with `-raw` and it works as well!

**Comment by Chiel92** [comment]
I'm not sure what's the generally preferred option here. I can imagine that for many applications it is desirable to translate special characters into entities. There must be a reason I think that tidy has this as the default behaviour. So unless there are good reasons to change it, I suggest that you use a custom format definition for this with whatever options you like.
