### ISSUE TITLE
Formatter chooses clang while astyle is preferred formatter

### ISSUE THREAD

**Issue by gbonnema** [Chiel92/vim-autoformat#197]
Hello,

I am in general content with vim-autoformat, except that it choses the wrong formatter only for headers. For c sources it uses the astyle (including the `~/.astylerc` which I do not have to define within vimrc).

Why would it chose correctly for .c files and not for .h files?

The relevant portion of my .vimrc is:

`augroup projects`
`	" remove all 'projects' commands (prevent duplicate definition)`
`	autocmd!`
`	autocmd BufWrite * :Autoformat`
`augroup END`
``
`set tabstop=4`
`set softtabstop=4`
`set shiftwidth=4`
`set noexpandtab`
``
`set colorcolumn=110`
`highlight ColorColumn ctermbg=darkgray`

`" Comment out the next line to get more info on autoformat processing`
`let g:autoformat_verbosemode=1`
`let g:formatdef_my_custom_c = '"astyle"'`
`let g:formatters_c = ['my_custom_c']`
`let g:formatdef_my_custom_h = '"astyle"'`
`let g:formatters_h = ['my_custom_h']`

`" autocmd FileType am let b:autoformat_autoindent=0`
`" autocmd FileType am let b:autoformat_retab=0`
``
`let g:autoformat_autoindent = 0`
`let g:autoformat_retab = 0`
`let g:autoformat_remove_trailing_spaces = 0`
``

The output when writing to a .h file is:

`edit.h [+]                                                                             79,33          16%`
`Trying definition from g:formatdef_clangformat`
`Evaluated formatprg: clang-format -lines=1:365 --assume-filename="/home/data/gbonnema/projects/c/xwpe-guu
s/src/edit.h" -style="{BasedOnStyle: WebKit, AlignTrailingComments: true, UseTab: Always}"`
`Using python 2 code...`
`"edit.h" 347L, 9307C written`
`Press ENTER or type command to continue`
``

The output when writing to a .c file is:

`we_find.c [+]                                                                          24,46           0%`
`Trying definition from g:formatdef_my_custom_c`
`Evaluated formatprg: astyle`
`Using python 2 code...`
`"we_find.c" 226L, 6327C written`
`Press ENTER or type command to continue`
``

Any ideas?

Kind regards, Guus Bonnema.

**Comment by Chiel92** [comment]
When in `edit.h`, what is the output of `:echo &ft`?

**Comment by gbonnema** [comment]
It says cpp.

**Comment by Chiel92** [comment]
That is a major hint. You posted that you defined `let g:formatters_c = ['my_custom_c']`, which is for `c` filetypes. But vim detects your code as `c++`.  So make sure that vim sees your header files as `c` code, or use `let g:formatters_cpp = ['my_custom_c']` instead.

**Comment by gbonnema** [comment]
Hi Chiel,

Ok, I will make the cpp formatter the same as the c formatter. 

Still I wonder whether I could have different formatters for c and for cpp, if vim always recognizes header files as cpp?

Also I don't understand why it didn't pick the formatter I defined for .h files (`let g:formatters_h) which was`astyle as well. Shouldn't that have prevented this?

**Comment by Chiel92** [comment]
Wait I messed up. It's your header files that don't work. Correcting my post above...

**Comment by Chiel92** [comment]
I don't know why your header files are detected as cpp. Try googling on that.

**Comment by gbonnema** [comment]
I will start digging, The other plugin I use is Ycm (Youcompleteme) for autocompletion. If I find anything I will let you know on this issue. Thanks for your time.
