### ISSUE TITLE
"fallback to vim's indent file " is dangerous on plain text

### ISSUE THREAD

**Issue by Huarong** [Chiel92/vim-autoformat#198]
When editing a plain text, the tab are modified when I save the file, which is very dangers. For most plain texts need not formatting.

Although we can turn this off with config, but I still suggest turn this off by default.

**Comment by Chiel92** [comment]
What do you mean with 'the tab are modified'?

**Comment by Huarong** [comment]
My Vim will turn tab into four space when I am writing. I believe a lot of people have this setting.

When I open a plain text containing `tab` characters, modify nothing, and then save with vim-autoformat. The "fallback to vim's indent file" action will change all the `tabs` to spaces with no warnings.

Plain texts are not like `codes`. They have no need to be formatted.

So I suggest to turn the `fallback` action off by default.

**Comment by Chiel92** [comment]
If you have `expandtab` set to true for plain text, then it makes sense to convert tabs to spaces if you ask vim-autoformat to format you text. If you would type things, vim would convert your inserted tabs to spaces too. 

More generally, vim-autoformat is by default configured to do the most sensible thing when `:Autoformat` is executed, based on your vim settings. If you have more exotic wishes, you can configure things differently.

If you don't want the fallback, then maybe you shouldn't have executed the command in the first place. And when you start tweaking things like adding autocmds, then you are expected to be savvy enough to simply turn off the fallback features.

And I disagree about regular text being inherently different from code in this respect. Even plain text has layout features like e.g. line-width, indentation size, indentation characters.
