### ISSUE TITLE
python3 checks seems wrong on re.search

### ISSUE THREAD

**Issue by 3xp10it** [Chiel92/vim-autoformat#199]
after I set:
`let g:syntastic_python_python_exec = 'python3'`
in .vimrc,when I open a python file as below:
<img src="http://chuantu.biz/t6/3/1502702614x2728309460.png">
it tells me line24's below code has invalid syntax
`if re.search(r"server is vulnerable",a,re.I):`
but in python3 it's ok to use as upon's re.search,is this a bug?

**Comment by Chiel92** [comment]
Shouldn't you ask in the syntastic repo instead? This is vim-autoformat.
