### ISSUE TITLE
python3 not being used (macos sierra)

### ISSUE THREAD

**Issue by niftylettuce** [Chiel92/vim-autoformat#202]
upon `brew install python3` and reboot/source file ... it does not use python3, only uses python2 blocks

**Comment by Chiel92** [comment]
Can you run python 3 in vim? `:py3 print(1)`

**Comment by niftylettuce** [comment]
@Chiel92 No, it says this command is not available in this version.  I'm on vim 8.x

**Comment by Chiel92** [comment]
Then if you run `:version` in vim, you will probably see `+python`, but `-python3`. Correct?
If that is the case, you need a vim version with python3 supported compiled in.

**Comment by niftylettuce** [comment]
correct:

<img width="88" alt="screen shot 2017-08-15 at 4 45 56 am" src="https://user-images.githubusercontent.com/523141/29308668-a8cae2ca-8174-11e7-9333-b1c345be8aa0.png">
