### ISSUE TITLE
Support Prettitier 

### ISSUE THREAD

**Issue by alex-shamshurin** [Chiel92/vim-autoformat#204]
This issue is closed https://github.com/Chiel92/vim-autoformat/issues/191 so I open this one to make it work. It will be nice if `vim-autoformat` support prettitier via cli, but now I have `vim-prettitier` plugin and `:Prettitier` command works. How run it via  `vim-autoformat`?

**Comment by Chiel92** [comment]
What do you want to achieve? I'm not sure what you mean by "running pretier via vim-autoformat".
If you want the same key for either formatting command, just map your keys differently for the filetypes where you want to use prettifier.

**Comment by alex-shamshurin** [comment]
I'd like to use only one key binding for all file types. If file type is  'js' or 'jsx' I wish `Autoformat` run `:Prettier` command on these file types. How to achieve this? Could you help me how to configure it?

**Comment by Chiel92** [comment]
Try something like (untested)

```vim
map <F3> :Autoformat
au filetype javascript map <F3> :Prettifier
```

**Comment by alex-shamshurin** [comment]
Thanks a lot!

**Comment by alex-shamshurin** [comment]
```
noremap <F3> :Autoformat<CR>
noremap! <F3> <esc> :Autoformat<CR>

au filetype javascript,javascript.jsx,typescript,less,scss,css,json,graphql noremap <F3> :Prettier<CR>
au filetype javascript,javascript.jsx,typescript,less,scss,css,json,graphql noremap! <F3> <esc> :Prettier<CR>

```

Hmm, this config do not work. :Prettier runs on every file type, on VIM files also.

**Comment by iafisher** [comment]
If anyone else stumbles across this issue, you probably want

```vim
map <F3> :Autoformat
au FileType javascript map <buffer> <F3> :Prettier
```

with `map <buffer>` so that the special key binding [only applies to the current buffer](https://stackoverflow.com/a/6133388/3934904). Otherwise, if you open a JavaScript file and then open a Python file in a new buffer, Vim will still try to use Prettier for the Python file.

**Comment by alex-shamshurin** [comment]
>Otherwise, if you open a JavaScript file and then open a Python file in a new buffer, Vim will still try to use Prettier for the  Python file.

How is this possible if we use `Filetype` with javascript and other types which prettier supports ?
