### ISSUE TITLE
:Autoformat always marks buffer as modified.

### ISSUE THREAD

**Issue by fwip** [Chiel92/vim-autoformat#212]
Whether the buffer is changed or not, vim marks the buffer as having been modified (`:help modified`).

It would be nice if Autoformat were smart enough to compare the input & output and either not do the modification, or `:set nomodified` after the fact. 

The first option would play nicer with undos & the `'.` mark, but I don't know if the structure of this plugin would make that difficult.

**Comment by Chiel92** [comment]
I think it could be done, hopefully without too much performance impact for larger files. I will attend to this soon. Duplicate: https://github.com/Chiel92/vim-autoformat/issues/128

**Comment by Chiel92** [comment]
Would you care to check if https://github.com/Chiel92/vim-autoformat/pull/213 fixes the issue to your satisfaction?

**Comment by fwip** [comment]
Looks great, thank you!
