### ISSUE TITLE
Feature: suggest installation steps for npm/pip/ruby packages

### ISSUE THREAD

**Issue by mqudsi** [Chiel92/vim-autoformat#220]
This should be fairly easy and would make Autoformat a bit easier to get started with out of the box: if a formatter is easily installable via one of the popular environment-specific but os-independent package managers, Autoformat can emit a message "xxx not found. Hint: xxxx can be installed via `npm install -g xxx`" (or `pip install` or `gem install`, etc.)

**Comment by Chiel92** [comment]
I'm not against this, but I also feel that this feature solves a non-existent problem. So I'm not sure if it's worth the hassle. If you can implement this in a way that doesn't introduce additional housekeeping, I'm fine with this feature.

**Comment by Chiel92** [comment]
Closing as not an issue.
