### ISSUE TITLE
semistandard support for javascript & elixir support

### ISSUE THREAD

**Issue by arcseldon** [Chiel92/vim-autoformat#221]
@Chiel92 - awesome project and one of my favourite plugins. Two requests :)

1). Am using `semistandard` for JavaScript - this is identical in many respects to `standard` which you already support out of the box. Would love to see this make the core plugin, so it just detects `semistandard` globally installed - identical to `standard`.

Have it working anyhow using custom settings -

```
" setup custom formatter for semistandard
let g:formatdef_semistandard_javascript = '"semistandard --fix --stdin"'
let g:formatters_javascript = ['semistandard_javascript']
```

If it could easily be added to core plugin, then save time & simplify `vimrc` settings.

2). Am working with [Elixir](https://elixir-lang.org/). In version 6 (newly released), there is now a [standard formatter](https://medium.com/blackode/code-formatter-the-big-feature-in-elixir-v1-6-0-f6572061a4ba) with the `mix` build tool out of the box.  So running something like `:!mix format %` on a file formats it. I can use this / setup a key binding in vim / nvim - but would really like `Autoformat` to do the right thing.

Tried using custom formatter as above for elixir (.ex or .exs) files and it failed. Is this something you could consider adding support for?  AFAIK, you currently don't have `Elixir` support. If you know a quick way to do it with a custom settings, then that would also be really helpful.

Here is copy of what failed for me when I tried:

```
" setup custom formatter for elixir - mix format
let g:formatdef_mixformat_ex = '"mix format"'
let g:formatters_ex = ['mixformat_ex']
```

Also tried using `elixir` on the end, instead of `ex`

To be honest, been a little lazy and raised an issue rather than dig into the specifics of why it failed.

But if i set `let g:autoformat_verbosemode=1` I get this output:

`No formatters defined for supertype elixir`

Thank you for any assistance or recommendations.

**Comment by arcseldon** [comment]
Workaround settings for formatting without `vim-autoformat` support in case helps others:

```
autocmd FileType elixir  nmap <Leader>p :!"$CLEAR_COMMAND"; mix format "%"<cr>
```

**Comment by Chiel92** [comment]
1) I'd be glad to merge in a pull request that adds your definition to the defaults. Shouldn't be hard.
2) Does `mix format` read/write from/to stdin/stdout? Anyhow, `No formatters defined for supertype elixir` tells us that the filetype recognition fails already. What does `:echo &ft` print when having an elixir file opened?

**Comment by arcseldon** [comment]
@Chiel92 - thanks.

> What does :echo &ft print when having an elixir file opened?

It outputs `elixir`

**Comment by Chiel92** [comment]
Then your config should look like this

```
" setup custom formatter for elixir - mix format
let g:formatdef_mixformat_ex = '"mix format"'
let g:formatters_elixir = ['mixformat_ex']
```

**Comment by dsissitka** [comment]
Elixir support was added this morning. :)

**Comment by arcseldon** [comment]
Brilliant, thanks v.much !!
