### ISSUE TITLE
Custom formatter

### ISSUE THREAD

**Issue by BigfootN** [Chiel92/vim-autoformat#224]
Hello,

I tried to define my own formatter (uncrustify) with these options:

```vim
let g:formatdef_uncrustify = '"uncrustify -c ~/.config/uncrustify/uncrustify.cfg"'
let g:formatters_c = ['uncrustify']
let g:formatters_cpp = ['uncrustify']
```

But I had these problems:

```
Trying definition from g:formatdef_uncrustify_cpp
Evaluated formatpgr: uncrustify -c ~/.config/uncrustify/uncrustify.cfg
Using pyhton 3 code...
Fromatter uncrustify_cpp has errors: 'bParsing: 2033 bytes (2033 chars) from stdin as language C\n'
Definition in 'g:formatdef_uncrustify_cpp' was unsuccessful.
No format definitions were successful.
Removing trailing whitespacce...
Retabbing
```

I am using nvim:
```
NVIM v0.2.3-385-gb616ef9b2
```

Thank you very much in advance.

**Comment by Chiel92** [comment]
Can you check the output of stderr when you run that program manually on the shell?

**Comment by BigfootN** [comment]
Hello,

Thank you for your quick response. I found a solution with this configuration:

```
let g:formatdef_uncrustify_cpp = '"uncrustify -q -c ~/.config/uncrustify/uncrustify.cfg -l CPP"'
let g:formatters_cpp = ['uncrustify_cpp']
```

The `-q` is the option that solved my problem, it then only outputs the formatted file.

But I would like to know if there is a way to pass the file name as an argument and not the content of the file.

Thank you very much for your help.

**Comment by Chiel92** [comment]
> The -q is the option that solved my problem, it then only outputs the formatted file.

Do you mean that uncrustify writes to stdout, even when there are no problems?


> But I would like to know if there is a way to pass the file name as an argument and not the content of the file.

I'm not sure what you mean here. Why would you want to pass a filename?

**Comment by BigfootN** [comment]
Thank you for answer.

> Do you mean that uncrustify writes to stdout, even when there are no problems?

Without `-q` uncrustify, even without any problems, writes a message at the top of stdout. Autoformat then seems to think it's an error.

> I'm not sure what you mean here. Why would you want to pass a filename?

It would then be possible to have something like:

```
let g:formatdef_uncrustify_cpp = '"uncrustify -q -c ~/.config/uncrustify/uncrustify.cfg -f"'
let g:formatters_cpp = ['uncrustify_cpp']
```

with the `-f` option waiting for a filename as an argument (which would then be the current file).

Thank you very much in advance.

**Comment by Chiel92** [comment]
> with the -f option waiting for a filename as an argument (which would then be the current file).

Why would passing a filename be better than passing the file via the stdin?

**Comment by BigfootN** [comment]
Thank you for your answer.

> Why would passing a filename be better than passing the file via the stdin?

I was just curious on how it could be done. I never thought it would be better.

Thank you very much in advance.

**Comment by Chiel92** [comment]
The file on disk does not always contains the latest version of your file, unless you just executed `:write`. That is the main reason we want to pass the file from the vim buffer via the stdin.

However, some formatters need to know the full path to the file that is being formatted, in order to correctly determine formatting settings from config files. In that case, look at how the typescript formatter does it:

```
 let g:formatdef_tsfmt = "'tsfmt --stdin '.bufname('%')"
```

**Comment by BigfootN** [comment]
Thank you very much for your answer.

I now understand why it can cause problems.

Thank you very much.
