### ISSUE TITLE
Vim-autoformat breaks user marks

### ISSUE THREAD

**Issue by mboughaba** [Chiel92/vim-autoformat#228]
Hello,

Thanks for putting together this nice plugin.
I noticed that when calling Autoformat, user cursor position and last search are changed by the plugin.
This means mark `'.` and last search are not preserved.

It would be nice to implement a fix for this, fine for me if it is configurable and we keep the current behavior as default.

Please let me know if this is something you want to include in your plugin so that I can make a PR for it.

Cheers,
Mo.

**Comment by Chiel92** [comment]
We want to keep in the cursor position in place as much as possible. If you can improve on that, please do and send a PR! I think the relevant place in the code is here https://github.com/Chiel92/vim-autoformat/blob/298e7d5fa8c4c5a8cff830f4bb84d1b0ada87836/plugin/autoformat.vim#L300

At the moment we call winsaveview/winrestview around the command to try to put the cursor in a sane position.

What do you mean by "last search" is not preserved?

**Comment by mboughaba** [comment]
Thank you for the feedback, I will work on it.

### Regarding search history:
> What do you mean by "last search" is not preserved?

Say we search for `/test`, then call Autoformat then hit `/` + `Arrow Up` to get the last search.
One would expect `/test` however last search will contain something else.

I did extra testing with this plugin alone to ensure that Autoformat is the one breaking user's search history but I couldn't reproduce. This means it must be one of my other plugins.

Cheers,

**Comment by Chiel92** [comment]
@mboughaba I created a PR here: https://github.com/Chiel92/vim-autoformat/pull/251
Could you verify if this solves your issue?
