### ISSUE TITLE
perl6-tidy fails

### ISSUE THREAD

**Issue by mwgkgk** [Chiel92/vim-autoformat#238]
Messages:
```
Trying definition from g:formatdef_perl6tidy
Evaluated formatprg: perl6-tidy --indent-style=tab
Using python 3 code...
Formatter perl6tidy has errors: b'Usage:\n  perl6-tidy [--strip-comments] [--strip-pod] [--strip-documentation] [--indent-style=<Indent-Style>] [--indent-with-spaces] <filename> \n'
 Definition in 'g:formatdef_perl6tidy' was unsuccessful.
 No format definitions were successful.
 Removing trailing whitespace...
 Retabbing...
 7 lines indented
```
From shell, works fine, called like this:
```
  perl6-tidy --indent-style=tab hello.pl6
```
.vimrc:
```
let g:formatdef_perl6tidy = '"perl6-tidy --indent-style=tab"'
let g:formatters_perl6 = ['perl6tidy']
```
What's the best way to see what's the resulting command that's actually called?

Any sort of pointers or suggestions are appreciated :)

**Comment by sum01** [comment]
Does it support `stdin`? Because it needs to in order to work. Maybe there's a flag you can pass to use stdin.

**Comment by Chiel92** [comment]
>What's the best way to see what's the resulting command that's actually called?

Evaluated formatprg: perl6-tidy --indent-style=tab

And it does indeed need to support reading from stdin. Judging from the message `Usage:\n  perl6-tidy [--strip-comments] [--strip-pod] [--strip-documentation] [--indent-style=<Indent-Style>] [--indent-with-spaces] <filename>` that may not be the case.

**Comment by mwgkgk** [comment]
Thank you! Didn't realize it's piped, - hence the question about resulting command. Since the formatter asks for filename, there's no easy xargs hack to make this work.
