### ISSUE TITLE
How can i format code when start new line 

### ISSUE THREAD

**Issue by GooCoder** [Chiel92/vim-autoformat#245]
I havn't seen any options which can do this.

**Comment by Chiel92** [comment]
Just to be clear, do you want to format the whole code when you insert a new line character?

**Comment by GooCoder** [comment]
I'm sorry for my ambiguous description. I want to format the previous line code when i start a new line. Can you tell me how to do this? Now i have no choice but to execute `Autoformat` through a shortcut key.

**Comment by Chiel92** [comment]
If you use a formatter that accepts range arguments you can try figuring out the range corresponding to the previous line and passing that to the `:Autoformat` command. I'm not sure if there is an easy way to trigger this on a new line. Anyway, this is not a use case that is supported at the moment by vim-autoformat, so there is no builtin way to do this.
