### ISSUE TITLE
Support for CUDA file extension

### ISSUE THREAD

**Issue by renmengye** [Chiel92/vim-autoformat#257]
Would it be possible to add *.cu filetype support? Thanks!

**Comment by Chiel92** [comment]
If you know a formatter for that, you could provide a PR implementing this! (See readme on details for how to add your formatter)

**Comment by renmengye** [comment]
I don't need a new formatter, and to still use clang-format (like C lang), but have it recognize the extension *.cu, is that possible by modifying some vimrc settings?
