### ISSUE TITLE
Not an editor command: Putmessages

### ISSUE THREAD

**Issue by lihao2333** [Chiel92/vim-autoformat#258]
when I run `:Autoformat` in a python file, the output is 
`Not an editor command: Autoformat`
Here is my config. 
```
 let g:formatterpath = ['/usr/bin']
let g:formatdef_autopep8 = "'autopep8 - --range '.a:firstline.' '.a:lastline"
let g:formatters_python = ['autopep8']
let g:autoformat_verbosemode=1
```
I'm Install by vundle

**Comment by Chiel92** [comment]
I don't know. You most likely haven't installed it correctly, because it works for other people.
