### ISSUE TITLE
Autoformat doesn't work for large files

### ISSUE THREAD

**Issue by ag0r** [Chiel92/vim-autoformat#264]
When running :Autoformat on a file that is 1257 lines long it returns without error, but doesn't actually format. I have copied small parts of the file into separate files and Autoformat works correctly in that case, so I have ruled out possible strange issues with the way the code is written. I have also tried formatting smaller blocks of code directly in the file which also does not work. Is there any undocumented cap on the number of lines that Autoformat can handle in a file before it stops working?

**Comment by Chiel92** [comment]
It shouldn't matter, although I have experienced similar issues on windows. What environment are you working on?

**Comment by ag0r** [comment]
In the default vim installation on Mac 10.13.3. I actually just realized that it doesn't actually do nothing; it did fix the indentation for the if __name__ == "__main__": block at the end of the file.

**Comment by ag0r** [comment]
I have found the issue. There was some Jinja2 templating code in the file that was not indented like the python code was. Removing that let the autoformat command work correctly. Thanks for your help.
