### ISSUE TITLE
Unable to format Python code on vim8/python3.7

### ISSUE THREAD

**Issue by ywdblog** [Chiel92/vim-autoformat#266]
hello:

When I executed, the following error  is occurred

```
Error detected while processing function <SNR>34_TryAllFormatters[56]..<SNR>34_TryFormatterPython3:
line   58:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/subprocess.py", line 139, in <module>
    import _posixsubprocess
ImportError: /usr/local/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undef
ined symbol: PyTuple_Type
```
My system environment：

- VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 28 2019 11:06:46) Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl     -L/usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lpthread -ldl -lutil -lm    
- Linux ns 3.13.0-129-generic #178-Ubuntu SMP Fri Aug 11 12:48:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Python 3.7.0 (default, Jul  9 2018, 15:19:32)

notice：This is not a problem with autopep8 external programs，because i unstall autopep8

importan: on python2/vim7.4 ,vim-autoformat is ok 。

thanks

**Comment by Chiel92** [comment]
I think this issue is not caused by vim-autoformat, but a general vim issue: https://github.com/vim/vim/issues/2925
