### ISSUE TITLE
Prettier format on save

### ISSUE THREAD

**Issue by philFernandez** [Chiel92/vim-autoformat#267]
I installed prettier via homebrew on Mac OS. I have `autocmd BufWrite * :Autoformat` in my vimrc to run whichever formatter for the filetype that I'm currently in. For example, in python files whenever I write the file, this plugin automatically runs autopep8 on the file. I was hoping for the same integration with prettier and javascript, but it doesn't seem to be working. Am I missing something? Thanks

**Comment by Chiel92** [comment]
Whether the autocommand works or not has nothing do to with a specific formatter. If it doesn't work for prettier, then prettier doesn't work either when manually running `:Autoformat` on the file. Am I correct?

**Comment by philFernandez** [comment]
That is correct. Prettier doesn't work when manually running `:Autoformat` on the file either.

**Comment by Chiel92** [comment]
In that case you might want to troubleshoot that. Read the text at https://github.com/Chiel92/vim-autoformat#help-the-formatter-doesnt-work-as-expected for hints.
