### ISSUE TITLE
Can I have a configuration to call multiple formatters automatically instead of using :NextFormatter?

### ISSUE THREAD

**Issue by idgserpro** [Chiel92/vim-autoformat#270]
>  If you have multiple formatters installed that are supported for some filetype, vim-autoformat tries all formatters in this list of applicable formatters, **until one succeeds**

Can I configure somehow to something like **until *all* suceeds**? I can create an `augroup` that calls `:NextFormatter` to acomplish this, but then everytime is run I get a ["selected formatter"](https://github.com/Chiel92/vim-autoformat/blob/c203080645936e73b2124040bc963386eeb44f5e/plugin/autoformat.vim#L318) message. I would like to know if there's an elegant way to do it (instead of using multiple `:NextFormatter` and [`:silent` calls](https://vim.fandom.com/wiki/Avoiding_the_%22Hit_ENTER_to_continue%22_prompts)).

**Comment by Chiel92** [comment]
Would it be possible to create a bash script that chains the tools that you want to use? That way you have a single program that you can use as formatter.

**Comment by Ch00k** [comment]
I solved this by chaining multiple formatters like this:
```
let g:formatdef_multiple = '"isort - | black -q -"'
let g:formatters_python = ['multiple']
```

**Comment by idgserpro** [comment]
> Would it be possible to create a bash script that chains the tools that you want to use? That way you have a single program that you can use as formatter.

It's possible, but I was thinking about a configuration to avoid creating external bash scripts to acomplish this.

But since you're the maintainer of this project, feel free to close the issue. I'll try @Ch00k's suggestion as well. Thanks!

**Comment by Chiel92** [comment]
Yes, if you're in an environment where shell syntax works, then @Ch00k 's suggestion is superior to creating external scripts. This is also how I envisioned this to work when I wrote this tool, but I later learned that it may not work on windows.

**Comment by yuki-ycino** [comment]
I'm using this
```
function! s:autoformat_all() abort
  let l:formatter_global_var_name = 'g:formatters_' . &filetype

  if !exists(l:formatter_global_var_name)
    Autoformat
    return
  endif

  let l:formatter_buffer_var_name = 'b:formatters_' . &filetype
  let l:formatters = []
  execute 'let l:formatters = ' . l:formatter_global_var_name

  for l:formatter in l:formatters
    execute 'let ' . l:formatter_buffer_var_name . '= ["' . l:formatter . '"]'
    Autoformat
  endfor

  execute 'unlet ' . l:formatter_buffer_var_name
endfunction
command! AutoformatAll call <SID>autoformat_all()
noremap <Leader>a :<C-u>AutoformatAll<CR>
```
