### ISSUE TITLE
is it possible to only format the selected lines?

### ISSUE THREAD

**Issue by huaihuaiVV** [Chiel92/vim-autoformat#272]
I want use AutoFormat to only format the selected lines,
because I don't want to change another people's code .

the same request for autoIndent and autoretab,  only works on the selected lines,
not the whole file buffer .

Thanks for your great tool !

**Comment by Chiel92** [comment]
Some formatters support that. If you are interested in the technical details, read https://github.com/Chiel92/vim-autoformat#ranged-definitions

At the moment, only yapf, autopep8 and clang support it.
