### ISSUE TITLE
If keyword breaks formatting in comments or commands

### ISSUE THREAD

**Issue by yogeshlonkar** [Chiel92/vim-autoformat#276]
Auto-formatting breaks with use `if` keyword either in comments or in commands

**How to reproduce issue**

`:Autoformat` below bash script
```shell
#!/usr/bin/env bash

if [[ -z "somecondition" ]]; then
        if [[ -z "othercondition" ]]; then
                # this comment will break formatting as it has if in it
                echo "do something"
                fi
        fi
        if [[ -z "thircondition" ]]; then
                # below command will also break as it has .. keyword
                echo "if in string"
                fi

```
.vimrc
```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Plugins start
Plugin 'Chiel92/vim-autoformat'
call vundle#end()
filetype plugin indent on
```

**Expected**
Autoformat should ignore `if` in comments and commands while formatting

**Workaround**
Use `ìf` in comments
```shell
 # this comment will break formatting as it has ìf in it
```
Or add additional `fi` in comments for getting around `if` in commands
```shell
if [[ -z "thircondition" ]]; then
   echo "if in string"
   # fi
fi
```

**Comment by Chiel92** [comment]
vim-autoformat uses the builtin Vim indentation mechanism to format bash code, unless you specify a formatter yourself. If the indent script for bash doesn't behave appropriately, you should open this issue in the relevant repository, or contact the maintainer of this particular indent script.

Looking at `$VIM/vim81/indent/sh.vim` I see at the top

```vim
" Vim indent file
" Language:            Shell Script
" Maintainer:          Christian Brabandt <cb@256bit.org>
" Original Author:     Nikolai Weibull <now@bitwi.se>
" Previous Maintainer: Peter Aronoff <telemachus@arpinum.org>
" Latest Revision:     2018-03-26
" License:             Vim (see :h license)
" Repository:          https://github.com/chrisbra/vim-sh-indent
```

**Comment by yogeshlonkar** [comment]
thanks find fix for comment related. Opened https://github.com/chrisbra/vim-sh-indent/issues/20 issue for `if` in commands
