### ISSUE TITLE
How can I disable auto formatting for current vim buffer?

### ISSUE THREAD

**Issue by ChrisZou** [Chiel92/vim-autoformat#284]
Hi @Chiel92 , I use this vim plugin and has enabled the auto format on save function. Generally it's working very well and is of great help. That you for your great work.
However, I sometimes run into use cases that the format this plugin is doing for me is not suitable, for example, when editing `.ssh/config` file. The autoformat will format

```
Host myhost
    HostName mydomain.com
    User myusername
    IdentityFile mykeyfile
```

to

```
Host myhost
HostName mydomain.com
User myusername
IdentityFile mykeyfile
```

which is not what I want. I wonder how can I disable the `formatting on save` function temporarily for the current buffer in vim? I went through the guide and it seems it only tells how to disable formatting for a specific file type. While as I only want to disable it temporarily for the current buffer.

**Comment by Chiel92** [comment]
The global settings 

```
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
```

all have buffer local variants, namely

```
let b:autoformat_autoindent = 0
let b:autoformat_retab = 0
let b:autoformat_remove_trailing_spaces = 0
```

If you want to set these in a live vim session, you can type these lines into the cmd line mode in VIM (`:`).

If you do this regularly, maybe a create custom command disabling all three options is useful. If you need help doing this, let me know.

If you find that the fallback behavior is generally not useful to use, you may consider disabling these options globally, and enable them per filetype/usecase whatever.

**Comment by ChrisZou** [comment]
@Chiel92 Thank you! It works!😄😄
