### ISSUE TITLE
Can't autoformat shell scripts

### ISSUE THREAD

**Issue by maujim** [Chiel92/vim-autoformat#291]
Most of my shell scripts don't have a `.sh` file extension so they don't get auto formatted. Is there anyway to work around this?

**Comment by Chiel92** [comment]
Yes, you can tell Vim the filetype of your program. To do it by hand simply say `:set ft=sh` or the like. 

But most of the time Vim does a decent job of autodetecting the filetype. If that doesn't work in your case, google around for `vim filetype detect`, or read [this blog about content base filetype detection](https://blog.afoolishmanifesto.com/posts/content-based-filetype-detection-in-vim/).
