### ISSUE TITLE
add support to swift

### ISSUE THREAD

**Issue by misakisuna705** [Chiel92/vim-autoformat#293]
When Apple release sourcekit-lsp, swift can be truly developed in vim some day.
So, I think vim-autoformat can support swift too.

According to sbdchd/neoformat, formatter could be nicklockwood/SwiftFormat.

Thank you!

**Comment by Chiel92** [comment]
That sounds indeed like an option. If you want to integrate it into vim-autoformat, have a look at the README. Once you think that your definition would be beneficial to others, you can create a PR for it to add it to the defaults.
