### ISSUE TITLE
I want to use it only in Python

### ISSUE THREAD

**Issue by luhuanxml** [Chiel92/vim-autoformat#296]
When I use AutoFormat, it always formats code snippets in my markdown. That's what I don't want.
like this! like this ! like this !
![image](https://user-images.githubusercontent.com/19920279/77335194-d1100f00-6d60-11ea-97ff-820a7a21bcaa.png)

**Comment by Chiel92** [comment]
What format program are you trying to use, and can you provide debug info as listed in the README.md?

**Comment by Chiel92** [comment]
Closing until further info provided
