### ISSUE TITLE
autoformat doesn't detects file type from tabs

### ISSUE THREAD

**Issue by Daksh14** [Chiel92/vim-autoformat#299]
When doing `:Autoformat` on a C# file, it formats it weirdly but when you specify the syntax like `:Autoformat C#` then it works correctly. This especially gives problems with the `au BufWrite * :Autoformat` as it could indent any file incorrectly. 
Any fix?

**Comment by Chiel92** [comment]
What do you mean by "from tabs"?

**Comment by Chiel92** [comment]
Closing until further info provided.
