### ISSUE TITLE
html-beautify defaults does not honor text width

### ISSUE THREAD

**Issue by sak96** [Chiel92/vim-autoformat#306]
current [defaults](https://github.com/Chiel92/vim-autoformat/blob/master/plugin/defaults.vim#L316) should have had [-w flag](https://github.com/beautify-web/js-beautify#css--html)

> let g:formatdef_htmlbeautify = '"html-beautify - -".(&expandtab ? "s ".shiftwidth() : "t").(&textwidth ? " -w ".&textwidth : "")' 

is there something i missed ?

**Comment by Chiel92** [comment]
> current defaults should have had -w flag

If this is a valid flag, you could provide a PR adding this mapping.

**Comment by sak96** [comment]
raise a pr #307.
for more details on -w flag check [here](https://github.com/beautify-web/js-beautify#css--html)
