### ISSUE TITLE
Miss indication of failed formatting

### ISSUE THREAD

**Issue by mxgrn** [Chiel92/vim-autoformat#311]
I'm using vim-autoformat with Elixir, and I can't figure out how to make it show the warning/error when `mix format` _fails_ .

If I set `let verbose=1` then I see notifications also on successful formatting, which I would like to avoid.

The formatting is triggered by `au BufWrite * :Autoformat`.

**Comment by Chiel92** [comment]
The verbose flag is meant to debug problems when the formatter isn't working. When the formatter is correctly installed and works correctly etcetera, it isn't supposed to give errors at random. Why would mix format be failing in your case?

**Comment by mxgrn** [comment]
> Why would mix format be failing in your case?

Because the source code it's trying to format is invalid. E.g. has `do` without `end`.

**Comment by Chiel92** [comment]
Formatprograms are not meant to detect syntax errors and report on them. They should do a best effort in formatting the code, and that is indeed what the vast majority of them do. This is how vim-autoformat was designed to work as well. Perhaps you could integrate an Elixir linter into Vim using e.g. [syntastic](https://github.com/vim-syntastic/syntastic)? In this setup you would let vim-autoformat fail silently while syntastic notifies you about the problems in your code.

**Comment by mxgrn** [comment]
[https://github.com/mhinz/vim-mix-format](https://github.com/mhinz/vim-mix-format) does display errors from the formatter in a window. Not sure I share the point of view that a (good) formatter should never check the syntax, but I get your point, closing the issue.
