### ISSUE TITLE
.sc filetype not recognised

### ISSUE THREAD

**Issue by rjaduthie** [Chiel92/vim-autoformat#325]
Before you create an issue, please read and follow the troubleshooting steps [listed here](https://github.com/Chiel92/vim-autoformat#help-the-formatter-doesnt-work-as-expected).

I'm trying to set up a custom formatter for .sc files as Scala scripts.  I have set up the formatter for .scala files, which works fine.  I want the sc formatter to use the same as scala.  In .vimrc:

```bash
let g:formatdef_scalafmt = '"scalafmt --stdin"'
let g:formatters_scala = ['scalafmt']
let g:formatters_sc = ['scalafmt']
```
If I'm in a file called test.scala, `:CurrentFormatter` gives: `Selected formatter: scalafmt`
If I'm in a file called test.sc, the result is [#323](the same as reported in this issue)

I've turned on verbose mode and, when trying `:CurrentFormatter` in the .sc file I get:
```bash
Error detected while processing function <SNR>13_CurrentFormatter[1]..<SNR>13_find_formatters:
line   43:
No formatters defined for supertype 
line   58:
No formatters defined for filetype ''.
Error detected while processing function <SNR>13_CurrentFormatter:
line    5:
E684: List index out of range: 0
```

It looks like the filetype is not being recognised.  Is this a fair diagnosis?

**Comment by Chiel92** [comment]
You can check that hypothesis by printing the filetype: `:echo &ft`.
To fix it you can add this to your vimrc (untested)

```vim
autocmd BufRead,BufNewFile *.sc set filetype=scala
```

**Comment by rjaduthie** [comment]
For information:
`:echo &ft` in [...].scala file gives "scala", but in [...].sc file gave nothing... but the fix works (*).  **Thank you!**

(*): of course, I had to re-open (`:e`) the .sc files that were already open after I changed the .vimrc and sourced it (`:source $MYVIMRC`).
