### ISSUE TITLE
Add support of black-macchiato

### ISSUE THREAD

**Issue by nkcfan** [Chiel92/vim-autoformat#329]
https://github.com/wbolster/black-macchiato is a simple wrapper around `black`.

I notice vim-autoformat already support `black`, but it does not support formatting range. `black-macchiato` just works on a code snippet, removing its indentation and formatting. `black-macchiato` does not have argument to specify the begin/end range on command line.

Wondering if vim-autoformat could add support of black-macchiato, and make the `black` support on both whole buffer and a range.

**Comment by Chiel92** [comment]
Yeah, we support that. Have a look at how the autopep command is implemented:

```vim
 let g:formatdef_autopep8 = '"autopep8 -".(g:DoesRangeEqualBuffer(a:firstline, a:lastline) ? " --range ".a:firstline." ".a:lastline : "")." ".(&textwidth ? "--max-line-length=".&textwidth : "")'
```

Also see the respective README section: https://github.com/Chiel92/vim-autoformat#ranged-definitions
