### ISSUE TITLE
Better document custom program formatting variable names

### ISSUE THREAD

**Issue by dellis23** [Chiel92/vim-autoformat#33]
I spent a while (okay fine, 15 minutes or so) trying to debug why the setting `formatprg_args_js` wasn't working.  I checked, and the documentation says it should be the filetype, so I wasn't sure what was wrong.  Finally I dug into the source code and realized it should actually be `javascript`.  Something making this a bit more clear would be nice.

**Comment by Chiel92** [comment]
The readme says that the format for the variables is `g:formatprg_<filetype>`, and that's exactly what it is. The vim filetype for javascript files is `javascript` not `js`. Try `:echo &ft` in a javascript file.

If you still feel the readme is not clear enough about this, I'm open to suggestions. Just send me a pull request, I'll have a look at it.
