### ISSUE TITLE
python expression is invalid (noob)

### ISSUE THREAD

**Issue by 992379555** [Chiel92/vim-autoformat#330]
I followed this step
        And add the following configuration in your .vimrc
        let g:python3_host_prog=/path/to/python/executable/

And I got this:
     Error detected while processing /Users/abc/.vimrc:
    line    8:
    E15: Invalid expression: /path/to/python/executable/

how to solve it, thanks

**Comment by Chiel92** [comment]
`/path/to/python/executable/` has to point to your python installation, don't use that literal string.
