### ISSUE TITLE
Last commit produces endless loop in startup

### ISSUE THREAD

**Issue by Grueslayer** [Chiel92/vim-autoformat#337]
After updating to latest version my Vim does not start anymore. It hangs while initializing this plugin

~~~
call plug#begin(g:vimuserrtp . '/bundle')
...
Plug 'Chiel92/vim-autoformat'
...
call plug#end()
~~~

~~~
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 23 2020 18:28:12)
MS-Windows 64-bit GUI/console version with OLE support
Included patches: 1-2198
~~~

**Comment by Chiel92** [comment]
That doesn't sound fun. I can't reproduce unfortunately. Can you confirm that it is actually the latest commit from @SilverRainZ ? In that case that should be reverted.

**Comment by SilverRainZ** [comment]
I am sorry about that :'( the reason should be that I only consider about *nix but ignore windows.

**Comment by Chiel92** [comment]
I've reverted the commit
