### ISSUE TITLE
New default verbose mode settings seem a little too obtrusive

### ISSUE THREAD

**Issue by btalb** [Chiel92/vim-autoformat#338]
Commit #336 adds a lot of spam to auto-formatting by default.

For example, formatting my `.vimrc` now prints these errors:
```
Error detected while processing function <SNR>40_TryAllFormatters[5]..<SNR>40_find_formatters:
line   43:
No formatters defined for supertype vim
line   58:
No formatters defined for filetype 'vim'.
```

Python also does similar, spitting out errors about formatters not being found which I don't use anyway (`yapf` still successfully formats the file, there's just a lot of 'noise' with it).

The changes look great, and will be useful for debugging pesky formatters that aren't playing nice.

I'm just not sure [this part of the change](https://github.com/Chiel92/vim-autoformat/blob/419dca7126940b7d468d528f8519608cd5936c53/plugin/defaults.vim#L21) was for the best.

Thoughts?

**Comment by Chiel92** [comment]
It seemed I overlooked that defaultvalue change while reviewen. Thanks for reporting. It should be fixed now.
