### ISSUE TITLE
Add Objective-C support

### ISSUE THREAD

**Issue by alexdunn** [Chiel92/vim-autoformat#34]
[astyle](http://astyle.sourceforge.net/astyle.html) also supports Objective-C.  

I tested it, and it seems to work just fine on the command-line:
`astyle <myObjCFile.m>`

However, in vim when I execute :Autoformat, I get the fallback vim auto indent rather than astyle's output.  Adding this to my .vimrc did the trick: 
`let g:formatprg_objc= "astyle"`

**Comment by Chiel92** [comment]
Looks like that support is added in version 2.04 indeed. My version of astyle (from the ubuntu 14.04 repositories) is only 2.03 and therefore doesn't support objective-c. Nevertheless it would be a very good thing to have a default definition for it.

Since I'm not familiar with objective-c, would you mind creating a pull request with a working definition? It shouldn't be hard: just copy the definition for C++ in `plugin/defaults.vim` and tweak a bit.

**Comment by alexdunn** [comment]
Hmm... running astyle on several of my Objective-C source files shows that it currently does very little, and what little it does is [inconsistent](https://sourceforge.net/p/astyle/bugs/333/).  

It looks like [Uncrustify]() and [clang-format](http://clang.llvm.org/docs/ClangFormat.html) are the formatters of choice for Objective-C.  

Using clang-format with this .clang-format has worked very well for me: 
```
BasedOnStyle: Chromium
AlignTrailingComments: true
BreakBeforeBraces: Allman
ColumnLimit: 0
IndentWidth: 4
KeepEmptyLinesAtTheStartOfBlocks: false
ObjCSpaceAfterProperty: true
ObjCSpaceBeforeProtocolList: true
PointerBindsToType: false
SpacesBeforeTrailingComments: 1
TabWidth: 8
UseTab: Never
```

Uncrustify with [this](https://github.com/dijkst/uncrustify-config-ios) config has similar results.

However, either of these would require adding a new recommended third party tool in the README, and I'm sure being able to customize the config would be important to users.

**Comment by Chiel92** [comment]
Adding another recommended third party tool is not a problem at all. The main purpose of this plugin is to make it easier to integrate formatting programs into vim. One way of doing that is by providing sane default configurations, which can also serve as an example for custom configurations.

If you think that e.g. clang-format would do better than astyle for objective-c, I'm fine with that.

**Comment by Chiel92** [comment]
Having a look at clang-format, I see that config can be specified in a file.
If the user wants that, he could add the line 
```vim
g:format_args_expr_objc = '"-style=file"'
```
to his `.vimrc`.
