### ISSUE TITLE
Please add fish-shell script support using fish builtin fish_indent command

### ISSUE THREAD

**Issue by c02y** [Chiel92/vim-autoformat#344]
```
let g:formatdef_fish_indent = '"fish_indent -"'
let g:formatters_fish = ['fish_indent']
```
it is not working, and if you make it work, I'm hoping it could be put into the vim-autoformat code.

**Comment by Chiel92** [comment]
Please follow the steps outlined here: https://github.com/Chiel92/vim-autoformat#help-the-formatter-doesnt-work-as-expected

**Comment by c02y** [comment]
https://github.com/Chiel92/vim-autoformat/pull/345
