### ISSUE TITLE
The way the Autoformat command is specified does not work in vim 7.2(.330)

### ISSUE THREAD

**Issue by derflocki** [Chiel92/vim-autoformat#38]
The way commit 5a17715cfcec778b61649a63b58e4fe946c8aed3 changed the creation of the Autoformat command does not work in vim 7.2. I get the following error:

    E180: Invalid complete value: filetype Autoformat call s:Autoformat(<f-args>)

Reverting back to 

    command! Autoformat call s:Autoformat()

and it works again.

**Comment by Chiel92** [comment]
That commit implements the feature that allows a filetype argument to be passed to the `:Autoformat` command, like `:Autoformat json`, in case the formatter you want to invoke doesn't match the buffer filetype. I can only guess that vim 7.2 didn't support `<f-args>` yet. The proper solution would be to upgrade to vim 7.3 or 7.4.
