### ISSUE TITLE
on-the-fly code-formatting

### ISSUE THREAD

**Issue by leandrocp** [Chiel92/vim-autoformat#40]
@Chiel92 see http://blog.unixphilosopher.com/2015/02/a-more-betterer-autosave-in-vim.html

I don´t know VimL but this `autocmd` may work for on-the-fly code formatting.

**Comment by leandrocp** [comment]
For now it´s working as expected:

`autocmd InsertLeave,TextChanged * if expand('%') != '' | Autoformat | endif`

**Comment by Chiel92** [comment]
I don't know why, but it only seems to do indentation, not formatting

**Comment by Chiel92** [comment]
Closing since no progress is made. Feel free to comment or reopen.
