### ISSUE TITLE
js-beautify fails with help text

### ISSUE THREAD

**Issue by visheshd** [Chiel92/vim-autoformat#43]
I opened a file using CtrlP. On using :Autoformat it returns `shell returned 1`

***And finally fills the buffer with the following js-beautify help text:***
Must define at least one file.
jsbeautifier.py@1.5.5

Javascript beautifier (http://jsbeautifier.org/)

Usage: jsbeautifier.py [options] <infile>

    <infile> can be "-", which means stdin.
    <outfile> defaults to stdout

Input options:

 -i,  --stdin                      read input from stdin

Output options:

 -s,  --indent-size=NUMBER         indentation size. (default 4).
 -c,  --indent-char=CHAR           character to indent with. (default space).
 -t,  --indent-with-tabs           Indent with tabs, overrides -s and -c
 -d,  --disable-preserve-newlines  do not preserve existing line breaks.
 -P,  --space-in-paren             add padding spaces within paren, ie. f( a, b )
 -E,  --space-in-empty-paren       Add a single space inside empty paren, ie. f( )
 -j,  --jslint-happy               more jslint-compatible output

**Comment by visheshd** [comment]
Oh its a javascript file

**Comment by Chiel92** [comment]
As [stated in the README](https://github.com/Chiel92/vim-autoformat#default-formatprograms), the python version of js-beautify is not supported by default.
Either you have to install the nodejs version of js-beautify, or you have to specifiy the formatter + arguments [manually](https://github.com/Chiel92/vim-autoformat#how-can-i-change-the-behaviour-of-formatters-or-add-one-myself).

**Comment by Chiel92** [comment]
I will update the readme to be more clear about this.

**Comment by visheshd** [comment]
Sorry, thanks for pointing that out and the plugin!

**Comment by Chiel92** [comment]
As from the new update, both version of js-beautify are supported.
