### ISSUE TITLE
Why even use fmtprogram?

### ISSUE THREAD

**Issue by jordwalke** [Chiel92/vim-autoformat#45]
Vim's `fmtprog` will cause undo/redo to be reset to the first line. It also modifies the buffer even when nothing was actually formatted. I wrote my own version that just shells out and finds the first line that actually changed and begins calling `setLine` from there. Why not take this approach with `vim-autoformat`?

**Comment by jalcine** [comment]
Perhaps for portability concerns? `formatprg` seems to cover that lightly. Also, in terms of handling undo/redo in Vim, aren't those actually command mappings? So hitting `gq` constantly would be saved in the undo history and can equate to equivalent changes. I think I might be misreading this portion in the Vim docs `undo.txt`

**Comment by Chiel92** [comment]
If you look at the source code, you see that for the most part `formatprg` merely acts as a variable. In `s:Autoformat(...)` its value is retrieved and manually used in a filter. But this vim filter has indeed the minor downsides that you talked about.

If your implementation fixes this, and doesn't introduce other unwanted side effects, it might be good to use that instead.

@jalcine Could you state the potential downsides that you suggest more clearly? I'm afraid I can't follow.

**Comment by Chiel92** [comment]
@jordwalke Since I can't think of any theoretical downsides, and @jalcine has not replied, I would be happy to merge in a pull request containing your implementation of this.

**Comment by jalcine** [comment]
Sorry, IRL caught up to me. I just figured that Vim's `fmtprg` was written with portability in mind (proper escaping for Windows and POSIX machines, et al). But a patch _still_ makes sense..
