### ISSUE TITLE
Multiple formatters per language out of the box

### ISSUE THREAD

**Issue by yoshuawuyts** [Chiel92/vim-autoformat#46]
When writing my own JS projects I use [`standard-format`](https://github.com/maxogden/standard-format), however when writing code for work we use [`jsfmt`](https://github.com/rdio/jsfmt). `Syntastic` has a whole list of [linters](https://github.com/scrooloose/syntastic/wiki/Syntax-Checkers) they support out of the box, whereas with `vim-autoformat` some logic needs to be written. Is having multiple formatters per language out of the box something you would consider having? Thanks!

**Comment by Chiel92** [comment]
Take a look at this issue: https://github.com/Chiel92/vim-autoformat/issues/37
If it doesn't entirely answer your question, please be sure to reopen this issue. Either way, feel free to continue commenting.

**Comment by yoshuawuyts** [comment]
Yup, I meant toggling. Being able to (programmatically) switch between different coding styles for projects would be rad. Even better would be if setting them up was as easy as installing the needed formatter globally (like with Syntastic). Does that make sense?

**Comment by Chiel92** [comment]
Let's see. How would you propose the toggling to work? A keymap for toggling through a list of defined formatprgs?

**Comment by yoshuawuyts** [comment]
Apologies if I sound like a broken record, but I think `Syntastic` nailed it. Here's an example of how it works.

Running `:SyntasticToggle` yields:

![screen shot 2015-03-28 at 12 02 17](https://cloud.githubusercontent.com/assets/2467194/6880835/58db2bfc-d542-11e4-9f32-aaee8c3d2884.png)

This exposes an array of available checkers (integrations available are available from core) and the currently enabled checker. Then you can choose which one to use by setting:
```viml
let b:syntastic_checkers = ['standard']
```
Or a dynamic version that switches checkers based on which dotfiles are available in root (switching between `jshint`, `eslint` and `standard` as a default):
```viml
autocmd FileType javascript let b:syntastic_checkers = findfile('.eslintrc', '.;') != '' ? ['eslint'] : findfile('.jshintrc', '.;') != '' ? ['jshint'] : ['standard']
```

I think that adding more integrations into core, having auto-detection which supported formatters are available in the shell, and allowing to set them through `.vimrc` should make `vim-autoformat` just as flexible as `Syntastic`. (Summing it up it does sound like a lot of work though, I hope I'm not suggesting something insane :o)

**Comment by Chiel92** [comment]
That sounds like a reasonable feature. So to sum up, we would have
- a bufferlocal list of available formatters, like `b:formatters` (the first formatter in the list would be the default at startup)
- a command to switch between the available formatters, like `:NextFormatter`
- for some formatters, some logic to move a certain formatter to the first position in the list, based on the presence of dotfiles

Is that correct?

**Comment by yoshuawuyts** [comment]
sorry about the delay. Yeah, that sounds about right ^^ Especially being able to programmatically switch them would be grand (never minded writing a bit of VimL myself ^^)

**Comment by Chiel92** [comment]
I don't have time to implement this at the moment, so I put the feature on the todo list.
Of course, if you're able to give it a try, that is appreciated and I will take time and have a look at it.
Otherwise this feature will have to wait.

**Comment by yoshuawuyts** [comment]
Haha, if I could, I would. My Vimscript just isn't quite there hah. Thanks for your time though, I'm really happy you at least find this worthy to implement! :D

**Comment by Chiel92** [comment]
Hi @yoshuawuyts,

I've made a start at tackling this issue. My current implementation is on the `multiple-formatters` branch.
The README.md on that branch has been updated to cover the new configuration variables.
Could you please have a look, and verify if it works for you?
If so, it would be nice to have a sane default definition for `jsfmt` as well. Could you provide one?

**Comment by yoshuawuyts** [comment]
Oh, that's super rad! I'm currently abroad though; I'm going to dig through this when I get home this weekend. Neat job regardless! :D

**Comment by Chiel92** [comment]
While at it, would you mind providing two default definitions for `jsfmt` and `standard-format`?

**Comment by Chiel92** [comment]
Closing. This issue should be fixed in the new update.
