### ISSUE TITLE
Format selected lines

### ISSUE THREAD

**Issue by dani-h** [Chiel92/vim-autoformat#49]
I'm not sure if this was mentioned before, but it would be neat to have the ability to indent select lines from visual mode. Since most of the formatters use stdin/stdout it seems possible to implement.

**Comment by Chiel92** [comment]
It already is possible, but the result is not always satisfactory. See issue #47.

**Comment by dani-h** [comment]
Ok thx

**Comment by Chiel92** [comment]
Just a small note: the new update enables this feature for formatters that are able to only format a certain range.
