### ISSUE TITLE
Use parent formatting rules for child file types

### ISSUE THREAD

**Issue by ezpuzz** [Chiel92/vim-autoformat#50]
For instance when I am editing a file that is of filetype `html.handlebars` I would like to use the `formatprg` options for the `html` filetype by default but currently I must manually set these values in vimrc to match that for html or autoformat will just use default vim indenting.

Could autoformat automatically use the before-the-dot filetype to set defaults for these "complex" filetypes?

**Comment by Chiel92** [comment]
A related issue was raised before. See https://github.com/Chiel92/vim-autoformat/issues/37.

To summarize the solution: you can define a formatter manually, for instance by copying the definition from the html default:

```vim
let g:formatprg_html_handlebars = g:formatprg_html
let g:formatprg_args_expr_html_handlebars = g:formatprg_args_expr_html
```

An alternative way to solve this is:

```vim
au filetype html.handlebars noremap <F3> :Autoformat html<CR><CR>
```

Both should work.

But reading your question again, it seems that you would vim-autoformat to do this automatically somehow. Maybe it makes sense to split the filetype by dots and check if their is a formatter available for these superfiletypes. I will put it on the todo list, and attend to it when I have time. Of course, if you can provide a pull request, that would be appreciated.

**Comment by Chiel92** [comment]
Let keep this open for the sake of clarity. :)

**Comment by Chiel92** [comment]
Hi @ezpuzz ,

I've made an attempt at solving this issue. My current implementation is on the multiple-formatters branch.
The README.md on that branch has been updated to cover the new configuration variables.
Could you please have a look, and verify if it solves your problems? In that case, this issue would be solved.

**Comment by Chiel92** [comment]
This should be fixed in the new update.

**Comment by ezpuzz** [comment]
sorry my environment changed, seems to be working
