### ISSUE TITLE
Out of box support for jscs

### ISSUE THREAD

**Issue by faceleg** [Chiel92/vim-autoformat#51]
http://jscs.info/

> JSCS is a code style linter for programmatically enforcing your style guide. You can configure JSCS for your project in detail using over 90 validation rules, including presets from popular style guides like jQuery, Airbnb, Google, and more.

Adoption rates are high, it'd be great to see support for this built into this plugin

**Comment by Chiel92** [comment]
Seems like a good idea. But currently `js-beautify` is set as the default formatter. So this will have to wait until multiple formatter support is implemented.

**Comment by faceleg** [comment]
What work is required to allow multi-formatter support?

**Comment by Chiel92** [comment]
I started working on it at branch `multiple-formatters`. 
This rewrite will also address some other issues and will break backward compatibility.
I expect it to be finished in a few days.

**Comment by Chiel92** [comment]
Could you provide a definition for jscs (just pasting it in this thread is fine by me)  and test it on the `multiple-formatters` branch? That would be greatly appreciated.

**Comment by faceleg** [comment]
Where in the plugin do I do this?

**Comment by faceleg** [comment]
I've added it and things seem to work.

**Comment by faceleg** [comment]
Something seems to have broke my autocmd:

`autocmd BufWritePre,FileWritePre *.js silent! :Autoformat<CR>`

**Comment by Chiel92** [comment]
@faceleg Sorry to respond so late.
Does the problem occur at the multiple-formatters branch, or at the master branch?

**Comment by faceleg** [comment]
Multiple formatters branch.

**Comment by Chiel92** [comment]
This is very peculiar. I will try to fix it.

**Comment by Chiel92** [comment]
Found it. You must not put the <CR> at the end. This should work:

```vim
autocmd BufWrite *.js :Autoformat
```

**Comment by faceleg** [comment]
Oh you mean the `<cr>`?

**Comment by Chiel92** [comment]
Oh, ha, it is interpreted as html :)
Yes, indeed

**Comment by Chiel92** [comment]
This should be fixed in the new update.

**Comment by faceleg** [comment]
Thanks, great work!
