### ISSUE TITLE
Error when running Autoformat on Ruby file

### ISSUE THREAD

**Issue by lashd** [Chiel92/vim-autoformat#53]
I've googled for a solution and am sure that I am probably doing something silly, but when running `:Autoformat`

I get the following output (verbosity turned on)
```
Error detected while processing function <SNR>12_TryAllFormatters:
line   27:
E117: Unknown function: rbeautify
E15: Invalid expression: rbeautify (&expandtab ? "-s -c ".&shiftwidth : "-t")
Formatter rbeautify has errors: /bin/sh: 0: command not found
. Skipping.
Failing config: '0'
```
The ruby-beautify gem is installed and on the PATH variable. From what I can tell line, 122 of autoformat.vim `formatprg = vim.eval('&formatprg')` evaluates to '0' instead of 'rbeautify' which is what is causing the message `Formatter rbeautify has errors: /bin/sh: 0: command not found` to be put in to stderr and printed on line 134 of autoformat.vim.

Again, I know this is likely to come down to me having gotten something very basic wrong. Any idea what it is?

Many thanks in advance.

**Comment by Chiel92** [comment]
Thanks a lot for your report! Somehow that definition got broken.
