### ISSUE TITLE
vim jumps to the top after formatting

### ISSUE THREAD

**Issue by Chiel92** [Chiel92/vim-autoformat#56]
Related to #55.
Possible solution: explicitly remember current line and jump to it after formatting.

**Comment by ngg** [comment]
This plugin already tries to do that with winsaveview().
#55 works perfectly for me.

**Comment by dvorszkid** [comment]
The linked solution (#55) works for me as well using astyle-2.05.1 and vim-7.4.712.

**Comment by Chiel92** [comment]
For astyle it seems to work somehow indeed, but for autopep8 it doesn't.
Besides, to me, the fix in #55 doesn't make sense as it just removes the range to be passed to the formatter function. The range has to be passed explicitly. http://stackoverflow.com/questions/10572996/passing-command-range-to-a-function

I proposed a new fix in https://github.com/Chiel92/vim-autoformat/pull/57.
Does this fix it for you as well?

**Comment by dvorszkid** [comment]
Yes, this also fixes the problem.

**Comment by Chiel92** [comment]
Pushed the changes. Thanks for the feedback!

**Comment by dvorszkid** [comment]
Thanks :)

**Comment by panzerdp** [comment]
@Chiel92 You're awesome! Thanks for the plugin.

**Comment by Wicked0ne** [comment]
This still seems to be affecting me. I'm on the latest version of this plugin and I'm using the autoformat when I save and if I save then try to undo I have to undo twice, once brings me to the top of the file, the other actually removes the change.

**Comment by ericlagergren** [comment]
I hate to "+1" issues, but I'm still seeing this issue. Additionally, when open the same file twice in vim, autoformat causes the second file to jump to the top if the first one is saved (but not the other way around).

**Comment by Chiel92** [comment]
@ericlagergren Could you please open a new issue for your problem, and specify in more detail what it is that you're seeing?
