### ISSUE TITLE
Is python3 supported?

### ISSUE THREAD

**Issue by giulioungaretti** [Chiel92/vim-autoformat#60]
I get an error saying a need +python, and I have +python3 . Is that expected.
My version of vim:
https://gist.github.com/giulioungaretti/79902b0edbb020096b57

**Comment by Chiel92** [comment]
It has not been tested with `+python3`, but I would expect it to work. I've just pushed a commit that extends the `+python` check with a `+python3` check. Could you update your vim-autoformat version and report if it works or not?

**Comment by giulioungaretti** [comment]
Updated, and same thing, but see the comment in the commit.

**Comment by Chiel92** [comment]
Fixed :)

**Comment by giulioungaretti** [comment]
Yes:
I think E319, is because vim expects python3 command instead of python. 

```vimscript

Error detected while processing function <SNR>53_TryAllFormatters..<SNR>53_TryFormatter:
line   11:
E319: Sorry, the command is not available in this version: python << EOF
line   12:
E492: Not an editor command: import vim, subprocess, os
line   13:
E492: Not an editor command: from subprocess import Popen, PIPE
line   15:
E492: Not an editor command: text = '\n'.join(vim.current.buffer[:])
line   16:
E492: Not an editor command: formatprg = vim.eval('&formatprg')
line   17:
```

**Comment by Chiel92** [comment]
Ouch. I hardly doubt there is a generic python command available.
An immediate ugly fix would be to branch on the python version, and have two almost-duplicate functions for each case.

**Comment by Chiel92** [comment]
Reference: http://stackoverflow.com/questions/30944325/generic-python-command-in-vim

**Comment by giulioungaretti** [comment]
yes, somehting like this https://github.com/giulioungaretti/vim-autoformat/tree/feature/python3 would work. But it's kind of ugly.

**Comment by Chiel92** [comment]
I pushed the ugly hack to the `dev` branch. Could you please check it out and see if it works for `+python3` as well?

**Comment by bor** [comment]
Might be would be better to done such work by raw vim script?

**Comment by giulioungaretti** [comment]
@Chiel92 dev branch works fine!

**Comment by Chiel92** [comment]
@bor The reason why that part is in python is because we use the subprocess library to communicate with the formatters, rather than using vim filters, which we did in the past. The latter has several issues.

@giulioungaretti Good. Then, however ugly the solution, I will push to master, since this is the only way that this can be fixed.

**Comment by giulioungaretti** [comment]
@Chiel92 I think so too. Eventually python 2 will finally die and then the ugly hack can be removed :D
