### ISSUE TITLE
Autoformat with autopep8 inserts newline at EOF

### ISSUE THREAD

**Issue by yggdr** [Chiel92/vim-autoformat#61]
Hi,

`:Autoformat` in a python file inserts a newline at the end of the file, which causes the pep8 syntax checker to complain. Since I set up to run both at BufWrite automatically, this creates quite a paradox situation. The newline isn't added by the autopep8 command line program, as verified by doing a `:%!autopep8 -`.

**Comment by Chiel92** [comment]
I can reproduce the issue. Will have a look as soon as I have time.

**Comment by jzipfler** [comment]
I think, I have a related problem.
For me, `:Autoformat` with clang-format or astyle_cpp seems to append the last character of the file.
Means:
If the line of my file is a "}", it appends an "}" on the next line.
If the last line is `//End of the file`, more and more e's gets appended each time `:Autoformat` is called.

I also tried to run clang-format and astyle separate, which causes no such problems.

**Comment by Chiel92** [comment]
@jzipfler I do not think that is related, as it also happens on the command line. Probably your astyle version is lower than 2.05. (`astyle --version`)

**Comment by jzipfler** [comment]
@Chiel92 I had version 2.04 installed at work (Debian). Upgraded to version 2.05.1 seems to fix it.
Thank you.

**Comment by Chiel92** [comment]
It appears that output of formatters may have an additional appending newline. To me it is not entirely clear when and why that happens. However, extra newlines are almost never required, while there are linters that complain about superfluous newlines, so I decided to remove one empty newline at the end of the file, if present. For all cases that I tested, this was a satisfactory solution.
