### ISSUE TITLE
How could I indent c++ pragma

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [Chiel92/vim-autoformat#64]
There was a version that would indent the c++ pragma like this:

```cpp
#include <omp.h>
#include <cstdio>
int main()
{
    #pragma omp parallel for
    for (int i = 0; i < 10; ++i)
    {
        puts("demo");
    }
    return 0;
}
```

instead of this:

```cpp
#include <omp.h>
#include <cstdio>
int main()
{
#pragma omp parallel for
    for (int i = 0; i < 10; ++i)
    {
        puts("demo");
    }
    return 0;
}
```

the current version won't do that and I want to configure to restore that feature.

I tried to add this code into `.vimrc` but it didn't work:

```vimL
let g:formatdef_mydef = '"astyle --mode=c --style=ansi -pcH".(&expandtab ? "s".&shiftwidth : "t")'
let g:formatters_cpp=['mydef']

```

**Comment by Chiel92** [comment]
For me it has the correct behaviour, like in your first example. What version of astyle do you have? (`$ astyle --version`)

**Comment by Alaya-in-Matrix** [comment]
It is version 2.03.

it seems if I specify `astyle` as my formatter:

```vimL
let g:formatdef_mydef = '"astyle --mode=c --style=ansi -pcH".(&expandtab ? "s".&shiftwidth : "t")'
let g:formatters_cpp=['mydef']
```

then the whole vim-autoformat get disabled, so currently, I am using:

```vimL
let g:formatdef_mydef = "'clang-format -lines='.a:firstline.':'.a:lastline.' --assume-filename='.bufname('%').' -style=\"{BasedOnStyle: WebKit, BreakBeforeBraces: Allman, AlignTrailingComments: true, '.(&textwidth ? 'ColumnLimit: '.&textwidth.', ' : '').(&expandtab ? 'UseTab: Never, IndentWidth: '.&shiftwidth : 'UseTab: Always').'}\"'"
let g:formatters_cpp    = ['mydef']

```

**Comment by Chiel92** [comment]
You should use version 2.05.1+
Previous astyle versions have some peculiarities which makes them incompatible with vim-autoformat since the rewrite that was needed some time ago. If the problem persists with the new version, please reopen.
