### ISSUE TITLE
c++ (clang-format) not using .clang-format file

### ISSUE THREAD

**Issue by arjanfrans** [Chiel92/vim-autoformat#67]
I have set `let g:formatdef_clangformat_objc = '"clang-format -style=file"'` in my .vimrc.

In my C++ project I have a `.clang-format` file. I open vim in this directory, open a .cpp file, perform `:Autoformat`. It formats, but it doesn't follow the rules I defined in my `.clang-format` file.

**Comment by Chiel92** [comment]
As of the patch in June 2015, you should give your definition its own name, and then link it to the correct filetype. The following should work.
```vim
let g:formatdef_myclangformat = "'clang-format -style=file'"
let g:formatters_objc = ['myclangformat']
```
