### ISSUE TITLE
Autoformat gofmt not work correctly

### ISSUE THREAD

**Issue by tthanh** [Chiel92/vim-autoformat#68]
When I use gofmt from bash, it display my code with tabspace like 4 or 8 but when use gofmt with autoformat in vim, my code still use global setting tabstop=2. How can I avoid tabstop when use with only golang.
![screenshot from 2015-08-02 14 02 04](https://cloud.githubusercontent.com/assets/8962973/9025112/4df8c208-391f-11e5-94ca-3e3a1da9c940.png)
![screenshot from 2015-08-02 14 03 16](https://cloud.githubusercontent.com/assets/8962973/9025113/4dff406a-391f-11e5-9e71-6b85a73f6caf.png)

**Comment by Chiel92** [comment]
I do not entirely understand the question. You want to display tabs like 4 spaces in vim for golang files?
What are your current indentation settings for golang files? (`shiftwidth`, `tabstop`, `expandtab`)

**Comment by tthanh** [comment]
I'm not settings for golang file, I use global settings in vimrc shiftwidth=tabstop=2. I use it for ruby and other stuff. Can I use this plugin without vimrc settings only for golang file?

**Comment by Chiel92** [comment]
Why don't you set shiftwidth and tabstop to 4 for golang files?

```vim
au filetype go set shiftwidth=4
au filetype go set tabstop=4
```

**Comment by tthanh** [comment]
I didn't know I can do that. Thank you so much.
