### ISSUE TITLE
Use shiftwidth() instead of shiftwidth

### ISSUE THREAD

**Issue by GrayShade** [Chiel92/vim-autoformat#75]
A `shiftwidth` value of `0` means that the value of `tabstop` should be used instead. I had it set like that in my `.vimrc` and auto-indent did not work.

I my case, `set sw=4` didn't work either, because something sets it back to `0`. For anyone else having trouble, I had to use `set &sw=&ts`.

**Comment by Chiel92** [comment]
I pushed the fix. Thanks for the report!

**Comment by GrayShade** [comment]
Verified working, thank you for the fix.

Anyway, it seems that vim's `=` doesn't like `sw=0`, but that's another story.
