### ISSUE TITLE
python3 Type error

### ISSUE THREAD

**Issue by chrcoe** [Chiel92/vim-autoformat#76]
On the master branch, when formatting a python file, I get the following error:

![format-error](https://cloud.githubusercontent.com/assets/770617/10368793/10b2ea94-6da5-11e5-914d-4752e58e242a.png)

I am using Python 3.5 on Arch Linux

When I switch to you dev branch, it works, but it adds an endline at the end of the file.  I remember seeing the endline problem come up and get fixed, but does not seem to be working for me.

It does work fine from command line usage of autopep8.

**Comment by Chiel92** [comment]
Thank you for the report. I was aware of the problem. The patch for windows line endings introduced this bug for vim with `+python3` support. Unfortunately I don't have python3 support and I lack the time to get my hands on it at the moment.

It's probably a very simple fix, where you have to convert some `str` objects to `byte` objects in the `TryFormatterPython3` functions, before assigning it to vims buffer.
Would you care to give it a try?

**Comment by chrcoe** [comment]
I'll take a look sometime this weekend and see what I find.

**Comment by chrcoe** [comment]
just kidding - it was bugging me so I thought I'd check into it sooner

**Comment by gblock0** [comment]
:+1:

**Comment by gblock0** [comment]
I'm getting:

```
Error detected while processing function <SNR>68_TryAllFormatters..<SNR>68_TryFormatterPython3:
line   32:
Traceback (most recent call last):
  File "<string>", line 27, in <module>
TypeError: 'str' does not support the buffer interface
```

Not sure if that is a similar/same error, but when I made the change using the [#77](https://github.com/Chiel92/vim-autoformat/pull/77) PR I get the following error: 

```
Error detected while processing function <SNR>68_TryAllFormatters..<SNR>68_TryFormatterPython3:
line   33:
Traceback (most recent call last):
  File "<string>", line 28, in <module>
TypeError: 'str' does not support the buffer interface
```

I'm trying to format a JavaScript file, if that helps.

If this is a different issue, please let me know and I can create a new issue for it.

Thanks!

**Comment by chrcoe** [comment]
I'm not 100% familiar with how it works for JavaScript formatting.

It might be related to #77 but it sounds like you were having this issue before you tried it?

**Comment by chrcoe** [comment]
@gblock0 I just tested it with a JS snippet and got this error (which is what I was getting in python before #77):

    Error detected while processing function <SNR>47_TryAllFormatters[41]..    <SNR>47_TryFormatterPython3:
    line   33:
    Traceback (most recent call last):
      File "<string>", line 28, in <module>
    TypeError: a bytes-like object is required, not 'str'

But I do *NOT* get it when formatting a python file anymore.

**Comment by chrcoe** [comment]
@Chiel92 @gblock0  I figured it out .. I inadvertently did not test the case where the line ending was not there and it converted funky ... creating a new pull request for this

**Comment by chrcoe** [comment]
@gblock0 can you test this on your end?

**Comment by gblock0** [comment]
Works like a charm! THANKS!

**Comment by chrcoe** [comment]
That is great to hear, thanks for letting me know!

**Comment by Chiel92** [comment]
Thank you @chrcoe for the help!
