### ISSUE TITLE
Support of vimscripts?

### ISSUE THREAD

**Issue by jamlen** [Chiel92/vim-autoformat#78]
This might seem really daft, but can I use a vimscript as the program to perform the auto formatting?

This script looks great for sql (http://www.vim.org/scripts/script.php?script_id=492) but I don't want different bindings for sql formatting.

**Comment by Chiel92** [comment]
No, that is not implemented. 
But can't you just bind the vim function to a key?

**Comment by jamlen** [comment]
I didn't want to have different bindings for different vimscripts plus the one for autoformat.

Would this make a good contribution? 

I guess there would need to be a way of identifying this formatter as a vimscript and to not run through the `s:TryFormatterPython` or `s:TryFormatterPython3` methods. I have never done any mods for vim but would be up for having a crack if you think it would be worth it.

**Comment by Chiel92** [comment]
I'm not sure I can follow. Say you have a vimscript function called `g:my_format_func` which formats your buffer for javascript files. Then you could put something like this line in `.vimrc`.

```vim
au filetype javascript map <F3> call g:my_format_func()
```

Then pressing <F3> will call your formatting function, only in javascript files. You don't have to use a different binding, you can just override it.
Do I interpret you situation correctly?

**Comment by Chiel92** [comment]
Closing until further information is provided.
