### ISSUE TITLE
Disabling for certain file types

### ISSUE THREAD

**Issue by sbdchd** [Chiel92/vim-autoformat#82]
I was wondering if / how you can disable vim-autoformat for certain file types, since the vim's indenting is not always the best.

Thanks.

**Comment by Chiel92** [comment]
What do you mean by 'disabling'? You can simply *not* run the `:Autoformat` command, can't you?

**Comment by sbdchd** [comment]
Oh, I didn't explain myself clearly.

I am using `au BufWrite * :Autoformat` to to run auto format on save, so I was wondering how I can disable autoformat for certain file types.

I guess this isn't really related to auto format itself so I will close the issue.

**Comment by Chiel92** [comment]
This may help you: http://stackoverflow.com/questions/6496778/vim-run-autocmd-on-all-filetypes-except
Good luck!

**Comment by dylburger** [comment]
For anyone who's trying to accomplish this, the below code in my `.vimrc` appeared to work for me. I'm restricting `:Autoformat` to run on file writes, only for Python code:

```
fun! AutoFormatSpecificFiles()
    if &ft =~ 'python'
        :Autoformat
    endif
endfun

au BufWrite * call AutoFormatSpecificFiles()  " Autoformat on writes
```

**Comment by dylburger** [comment]
Separately, thank you for the great plugin, @Chiel92 !
