### ISSUE TITLE
vim.error: string cannot contain new lines

### ISSUE THREAD

**Issue by dawnofthedev** [Chiel92/vim-autoformat#83]
Lately I've been seeing this error complaining about newlines preventing formatting. I use js-beautify (npm) and have tried with both python2 and 3. I use Windows 7 64bit. I've tried with and without neobundle lazy loading so I think you can ignore that part of the error.

![2015-10-26 12_53_28-gulpfile js](https://cloud.githubusercontent.com/assets/14855424/10734157/a1b759d2-7be0-11e5-84d4-86b46aae640b.png)

**Comment by Chiel92** [comment]
Thanks for your post. Could you please confirm that you have the latest version?
Moreover, could you post the error for pythnon 2? That would be easier for me to debug.

**Comment by dawnofthedev** [comment]
![2015-10-26 15_52_28-gulpfile js](https://cloud.githubusercontent.com/assets/14855424/10739149/9ae6c570-7bf9-11e5-8dbb-83b72ec2fcd5.png)

Not sure if that's what you meant (is there a way for me to get you more detailed logs?)

Yes I can confirm this is with latest version.

And thanks to you for the plugin!

**Comment by Chiel92** [comment]
What does `:echo &ff` say for you?

**Comment by dawnofthedev** [comment]
`unix` (even on Windows 7 64bit)

**Comment by Chiel92** [comment]
I'm suspecting that js-beautify returns unix line endings and that vim-autoformat tries to split lines on windows line endings (as you are on windows).

I think it could be solved by putting this part in a try/catch block. I will have a look at it later on.

**Comment by Chiel92** [comment]
I pushed a pragmatic fix to branch `dev`. Could you please check it out and report if this works for you?

**Comment by dawnofthedev** [comment]
It's working. Thanks.

**Comment by Chiel92** [comment]
Could you verify that its working for both python2 and python3? This is because my machines only run python2.

@IceNature, @chrcoe , @gblock0 Here is another crossplatform issue related to #71 and #76. If possible, would you be so kind to test if this patch does not break earlier achievements w.r.t. your specific use cases? It's on branch `dev`.

**Comment by dawnofthedev** [comment]
![gvim](https://cloud.githubusercontent.com/assets/14855424/10798120/c5f39fea-7d84-11e5-8cb6-b0f94f0c5359.png)

**Comment by chrcoe** [comment]
sorry same error as @dawnofthedev 
using python 3.5 in arch linux

**Comment by Chiel92** [comment]
I pushed a commit to `dev` that should fix this (For real now :)).
Would you mind to verify?

**Comment by dawnofthedev** [comment]
It works for me using npm js-beautify with Python 2 and 3 on Windows 7.

**Comment by chrcoe** [comment]
@Chiel92 I will try this out later tonight and let you know what I find

**Comment by chrcoe** [comment]
@Chiel92 sorry for the horribly late response!

I just pulled down the most recent dev branch fixes and that works for my use cases (formatting python, java, php, c, c++, XML, and JSON)

**Comment by IceNature** [comment]
Worked well on Windows7 with Py2 or Py3 (Astyle C/C++)

**Comment by Chiel92** [comment]
Pushed to master. Closing. Thanks for the help and the feedback!
