### ISSUE TITLE
Filename not passed to the typescript formatter

### ISSUE THREAD

**Issue by kuon** [Chiel92/vim-autoformat#84]
The default typescript formatter is:

`let g:formatdef_tsfmt = '"tsfmt --stdin %"'`

Which has for effect to call `tsfmt` with `%` as a filename (instead of the actual filename). This is a problem for `.tsx` files which are not formatted properly.

This can be checked by setting the formatter with verbose mode:

`let g:formatdef_tsfmt = '"tsfmt --verbose --stdin %"'`

and then after a format, there is at the top of the formatted file:

`file: %`

Which means the filename wasn't passed.

**Comment by kuon** [comment]
`let g:formatdef_tsfmt = '"tsfmt --stdin '.bufname('%').'"'`

Seems to fix the problem

**Comment by Chiel92** [comment]
Makes sense. Could you provide a pull request implementing this fix?

**Comment by kuon** [comment]
https://github.com/Chiel92/vim-autoformat/pull/85 Should fix it
