### ISSUE TITLE
BufWritePre autocmd not using autopep8 on python file when using neo-vim

### ISSUE THREAD

**Issue by RatanRSur** [Chiel92/vim-autoformat#88]
I have these two lines in my vimrc:

```
autocmd! BufWritePre *.py Autoformat
autocmd! BufWritePost * Neomake
```

After saving, `:messages` displays that both commands ran:

```
13 lines to indent...
14 lines indented
"flattenlist.py" 14L, 392C written
Neomake: python complete with exit code 0
Neomake: pep8 complete with exit code 1
```

However, the autoformatting is defaulting back to vim's in built indent functionality it seems like, instead of doing autopep8, which is what happens when I manually run `:Autoformat`.

**Comment by Chiel92** [comment]
Could you please set `g_autoformat_verbosemode` to 1 and see if it gives additional output in messages?

**Comment by RatanRSur** [comment]
With `let g_autoformat_verbosemode=1`, it still has the same output

**Comment by RatanRSur** [comment]
Also, I should mention that I'm using neovim, if that makes a difference

**Comment by Chiel92** [comment]
Sorry, I made a typo, it should have been `let g:autoformat_verbosemode=1` or alternatively `set verbose=1`.

**Comment by RatanRSur** [comment]
Wow, your debugging even mentions neovim haha

```
Error detected while processing function <SNR>18_TryAllFormatters..<SNR>18_find_formatters:
line   32:
No formatters defined for supertype '<CR> "figure out why this doesn't work in neovim
line   47:
No formatters defined for filetype '<CR> "figure out why this doesn't work in neovim'.
13 lines to indent...
14 lines indented
"flattenlist.py" 14L, 392C written
Neomake: python complete with exit code 0
Neomake: pep8 complete with exit code 1
```

**Comment by Chiel92** [comment]
It seems it has something to do with how neovim passed arguments. You could check that by substituting the line

```vim
    let ftype = a:0 ? a:1 : &filetype
```

with

```vim
    let ftype = &filetype
```

in plugins/autoformat.vim line 8.

**Comment by RatanRSur** [comment]
Yup, that fixes it.

**Comment by Chiel92** [comment]
> Will this stop vim-plug from being able to automatically update this though?

Yes. It is not a fix. It also disables the possibility to pass arguments to the `:Autoformat` command.

Since this seems like a bug in neovim, it should preferably be fixed there.
Nevertheless, I would be okay with a quick workaround to make things work in neovim as well. 
But as I'm not a neovim user myself I can't easily put this together. When I have time I may take some to look at it. Before that, if someone figures something out, please send a pull request.

**Comment by Chiel92** [comment]
It may be possible to branch on `has('nvim')` and define functions differently for each case.

**Comment by Chiel92** [comment]
Is this still an issue?

**Comment by Chiel92** [comment]
Please reopen if issue persists.
