### ISSUE TITLE
How to know which formatter is used?

### ISSUE THREAD

**Issue by omidfi** [Chiel92/vim-autoformat#89]
Hi, thanks for the nice plugin
I'm using this on vim to format my javascritp with JSCS. I get my code formatted, but wanted to know is there a way to find out what config file the jscs is using? I mean the path to the config file. 

Thanks,
Omid

**Comment by Chiel92** [comment]
Taking a look in `defaults.vim`, we can see that the default way of calling jscs is `jscs -x`, which, according to its CLI specification (http://jscs.info/overview), "will apply fixes to all supported style rules". Does this answer your question?

**Comment by omidfi** [comment]
Thank you @Chiel92  yes it does!
