### ISSUE TITLE
Async support for neovim?

### ISSUE THREAD

**Issue by gblock0** [Chiel92/vim-autoformat#91]
I was wondering if you had any plans on making vim-autoformat have async support for neovim?

**Comment by Chiel92** [comment]
I don't have any plans, and that probably won't change anytime soon.
However, I'm open to pull requests that implement such a feature without compromises.

Out of curiosity, why would you like to have this? Can you sketch a use case?

**Comment by gblock0** [comment]
Ideally I would like to run autoformat on BufWritePre, but I can't since its blocking and disrupts my flow.

**Comment by Chiel92** [comment]
A sidenote, don't you experience the bug issued in https://github.com/Chiel92/vim-autoformat/issues/88?

**Comment by gblock0** [comment]
Nope. Autoformat works great for me in neovim, but since it's synchronous I don't like running it every time I save a file.

**Comment by yang-datong** [comment]
> Nope. Autoformat works great for me in neovim, but since it's synchronous I don't like running it every time I save a file.


Yes, when I edit 1000 + lines of latex code, I will synchronously execute the Autoformat command (about 1-2 seconds) when writing to the file, and then perform the vimtex compilation operation, which is too slow,So I had to give up the automatic format command.
