### ISSUE TITLE
editorconfig doesn't apply

### ISSUE THREAD

**Issue by darrenhaken** [Chiel92/vim-autoformat#93]
Any ideas how to resolve this?

**Comment by Chiel92** [comment]
Could you please elaborate and at least specify what config is not applying?

**Comment by darrenhaken** [comment]
I have only started using Vim recently so you'll have to forgive me if I am doing a newbie move here.
I'm working on a Ruby project but it looked like the formatting was using 4 spaces instead of the default Ruby 4.

I noticed that I have a setting in my vimrc:
set shiftwidth=4

When I change this to 2 it seems like the formatting is working.

FYI I took a template VIM file with some default templates from Destroy All Software

Any ideas?

**Comment by Chiel92** [comment]
Ok, don't worry, let's see if we can sort this out.

> I'm working on a Ruby project but it looked like the formatting was using 4 spaces instead of the default Ruby 4.

I'm afraid I don't follow. Am I correct in assuming that the formatter uses 4 spaces and that you want 2 spaces?

**Comment by darrenhaken** [comment]
That's correct yes. 
I'm happy to share my vimrc file if it helps diagnose the issue.

**Comment by Chiel92** [comment]
If you want to have 2 spaces, you must set shiftwidth as such.
vim-autoformat checks these settings when calling the formatter.
Thus, you should add the following to your vimrc.

```vim
au filetype ruby set shiftwidth=2
```

Does that solve your issue?

**Comment by darrenhaken** [comment]
That's done the trick thanks for the help! I haven't seen that syntax before so I'll keep that in mind.

If I used an editorconfig file in the project would the plugin honour that?

**Comment by Chiel92** [comment]
What do you mean by "editorconfig file"? What kind of file are you referring to?

**Comment by darrenhaken** [comment]
See: http://editorconfig.org/

You create an editorconfig file which you store in your project folder.
The idea is that whatever IDE you use should honour the file and adjust it's spacing.

I often use Atom and IntelliJ and they both support this.

**Comment by Chiel92** [comment]
Since the editorconfig file sets corresponding vim options (assuming that you use https://github.com/editorconfig/editorconfig-vim#readme) and vim-autoformat takes the `shiftwidth` and the `expandtab` properties into account for ruby (check out defaults.vim) we can conclude that vim-autoformat honours the `indent_style` and the `indent_size` properties of editorconfig when using ruby-beautify.
