### ISSUE TITLE
format of source code removes all marks

### ISSUE THREAD

**Issue by krux02** [Chiel92/vim-autoformat#96]
Autoformat of the source code removes all marks.

steps to reproduce in normal mode:

```
:Autoformat                   //format to make sure the next call does nothing
mm                            //set the mark m
:marks                        //you see the mark m now
:Autoformat                   //does nothing now
:marks                        //now the mark is gone
```

note, whenever a files changes, and `autoread` is set, vim keeps marks at the same line number. That is at least better than removing them completely.

**Comment by Chiel92** [comment]
Agreed that this should be implemented. Not sure how to do this yet.

**Comment by krux02** [comment]
[clang-format.py](https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format.py) does this specialized for the clang-formater and written in python, but it gives you something you can port.

**Comment by tohou** [comment]
The [rust.vim](https://github.com/rust-lang/rust.vim) plugin also does this with rustfmt.

I don’t know much vimscript myself, but I believe the functionality is implemented in [this file](https://github.com/rust-lang/rust.vim/blob/master/autoload/rustfmt.vim). I hope this helps.

**Comment by Chiel92** [comment]
I'm currently going to the list of issues, and made a commit that seems to fix this issue. The branch is `write-read-viminfo`. @krux02 @tomhoule Care to verify that this solves the issue?

**Comment by krux02** [comment]
Sorry, but I use emacs now. Can't veryfy anymore.

**Comment by tomhoule** [comment]
And I use VSCode :/

**Comment by Chiel92** [comment]
Shame ¯\_(ツ)_/¯
I use Visual Studio (with vi mode) a lot these days, because it excels at .net languages. But occasionally, for things like python scripting, I fall back to good ol' vim 😄

**Comment by kashifrazzaqui** [comment]
This is issue isn't solved and I have the latest version of the plugin
