### ISSUE TITLE
Difference with vim-clang-format

### ISSUE THREAD

**Issue by Yamakaky** [Chiel92/vim-autoformat#98]
Is there any reason to prefer [vim-clang-format](https://github.com/rhysd/vim-clang-format) to vim-autoformat ?

**Comment by Chiel92** [comment]
From a quick look it seems that difference of vim-clang-format is that it provides some vim options which directly correspond to clang-format settings.
In vim-autoformat you customize by setting the entire argument list expression in a string.
Maybe there are other difference, I don't know.
In principle I would say there can be no theoretical advantage of vim-clang-format as long as you just want to format your text with a single command.
